import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/damaged-ford-fiesta-trailer-pickup-calgary.jpeg";
import farmImage from "@/assets/images/black-chevrolet-cash-car-sale-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Strathmore | Free Towing, Cash on Pickup", description: "Cash for junk cars in Strathmore and Wheatland County. We buy non-running, damaged and scrap vehicles and farm trucks, tow free, and pay at pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-strathmore" }, openGraph: { title: "Cash for Junk Cars Strathmore | Free Towing, Cash on Pickup", description: "Cash for junk cars in Strathmore and Wheatland County. We buy non-running, damaged and scrap vehicles and farm trucks, tow free, and pay at pickup.", url: "https://www.junkacar.ca/cash-for-cars-strathmore", type: "website", images: [{ url: heroImage.src, alt: "Damaged vehicle collected for cash near Strathmore" }] } };

const data: ServicePageData = {
  path: "/cash-for-cars-strathmore", label: "Cash for Cars Strathmore", h1: "Cash for Junk Cars in Strathmore — Free Towing Along the Trans-Canada",
  subhead: "We're about forty-five minutes east on Highway 1. In town or out on a Wheatland County farm, running or long retired, we'll give you a real number the same day, tow it free, and pay you before it goes on the deck.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "Damaged Ford Fiesta secured for junk car pickup near Strathmore", trustItems: ["Free Strathmore towing", "Wheatland County covered", "Same-day offers", "Cash at pickup"],
  sections: [
    { eyebrow: "Why Strathmore", title: "Life on Highway 1 and Irrigation Roads", intro: ["Strathmore vehicles lead two kinds of lives — one on the busiest highway in the country and one on the gravel grid of irrigated farmland. Both are hard in their own way."], cards: [
      { title: "The Trans-Canada is hard driving", text: <>A lot of Strathmore commutes into Calgary on Highway 1 — roughly a hundred kilometres round trip, most of it at highway speed, sharing the road with long-haul trucks. That traffic throws up gravel, chunks of tire tread and road debris all year, and sprays brine all winter.<br /><br />The result is a recognisable Strathmore vehicle: chipped and cracked windshield, pitted paint across the hood and front bumper, and corrosion underneath from years of highway spray. Cosmetically rough, often mechanically fine — until the kilometres finally catch up with the transmission or the engine.</> },
      { title: "Irrigation-district gravel", text: "Strathmore sits in the heart of land served by the Western Irrigation District, and the grid of gravel roads and canal access routes around it is where farm vehicles spend their lives. Washboard, dust and loose gravel wear suspension, steering components and undercarriages far faster than paved driving ever would." },
      { title: "Wheatland County farm trucks", text: "Grain, cattle and irrigated crops mean trucks of every size — half-tons, one-tons, grain trucks and service units. They work hard, they're rarely traded in, and when they're retired they usually stay in the yard beside the bins. A single visit often clears several." },
      { title: "Wind, dust and hail", text: "Open prairie means wind, and wind carries dust and grit that sandblasts paint and works into door seals and window channels. Summer hail tracks across the county as well, writing off vehicles that are otherwise perfectly sound." },
    ]},
    { eyebrow: "Valuation", title: "What Strathmore Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Highway commuter, high kilometres, still running", "$900 – $4,000"], ["Older car or SUV, non-running", "$300 – $1,200"], ["Farm half-ton, non-running", "$700 – $2,000"], ["Grain truck or one-ton, complete", "$1,000 – $3,500"], ["Hail-damaged, mechanically sound", "$1,500 – $8,000"], ["Three or more from one yard", "Per-vehicle offer improves"]] }, after: ["Weight sets the floor, and farm trucks are heavy. Salvageable parts — engines, transmissions, axles, boxes — push the number up. The catalytic converter is priced separately and can be a large share of the offer on a big truck.", "Chipped glass, pitted paint and a rough front end barely move our number, because we aren't pricing appearance. That's exactly why highway-worn Strathmore vehicles often do better with us than with a private buyer who's looking at the paint first."] },
    { eyebrow: "One call handles it", title: "Our Services in Strathmore", intro: ["From a highway commuter in town to a row of grain trucks out on the county, each of these services is available across Strathmore and Wheatland County — with free towing and payment on the day."], cards: [
      { title: "Junk Car Removal in Strathmore", text: <>A commuter car that&apos;s finally given out after years of Trans-Canada driving — or one that died on Highway 1 and is now sitting at a tow yard — is our most common in-town job. Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> collects from driveways in Lakewood or Wildflower and directly from local tow yards, so storage fees stop the day we pick up.</> },
      { title: "Scrap Car Removal in Strathmore", text: <>Farm trucks that have run the irrigation-district gravel for decades usually finish as scrap once the frame and undercarriage go. Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> clears them from Wheatland County yards and processes them properly, keeping oils and coolant out of land that drains into the canal system.</> },
      { title: "Cash for Scrap Cars in Strathmore", text: <>A grain truck or one-ton is one of the heaviest vehicles we buy, and weight is where scrap value starts. Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> shows how that weight, plus axles, engines and the catalytic converter, adds up — and why a chipped, sandblasted farm truck is still worth a proper offer.</> },
      { title: "Free Towing in Strathmore", text: <>The forty-five-minute run east costs you nothing, and neither does a long gravel approach out toward Rockyford or Carseland. <Link href="/free-towing-calgary">Free towing</Link> covers town, farm and tow-yard pickups alike, with no charge per vehicle when we clear a whole fence line.</> },
    ]},
    { eyebrow: "Local situations", title: "Situations We Handle Around Strathmore", cards: [
      { title: "“It broke down on Highway 1 and it's at a tow yard.”", text: "Storage fees add up every day. Give us the yard's address and the release details, and we'll collect it directly from there so the meter stops running." },
      { title: "“It's a grain truck that hasn't moved in years.”", text: "Grain trucks are heavy and parts-rich. Describe the make, model and size and we'll give you a real figure rather than a guess." },
      { title: "“There's a line of old vehicles behind the shop.”", text: "One trip, one payment. Tell us roughly how many and what you can identify, and we'll quote the group." },
      { title: "“It's registered to the farm.”", text: "Workable with signing authority for the farm corporation or partnership. Call first so it's ready on the day." },
      { title: "“The windshield is shattered and the paint's gone.”", text: "Irrelevant to us. We price weight and parts, not looks." },
    ]},
    { eyebrow: "Write-offs", title: "After a Highway 1 Collision or Write-Off", image: farmImage, imageAlt: "Black Chevrolet being assessed after a vehicle write-off near Strathmore", intro: ["Highway 1 east of Calgary sees its share of collisions — deer strikes at dusk, winter ditch runs, and rear-end impacts in slowdowns near the Chestermere and Strathmore exits. When the insurer writes the vehicle off, you usually have two choices: surrender it, or keep it as a buyback.", "If you keep it, you own a vehicle with salvage or non-repairable status that can't simply go back on the road. That's where we come in. Both statuses sell to us, and a newer vehicle with front-end deer damage often still has a healthy engine, transmission, rear half and interior — all of which carry real value. Have the insurer's paperwork ready and we'll give you a number the same day."] },
    { eyebrow: "Coverage", title: "Where We Collect in Strathmore and Wheatland County", cards: [
      { title: "In town", text: "Lakewood, Wildflower, Aspen Creek, Strathaven, Hillview, Kingsmoor, Brentwood, Edgefield, Lambert Estates, Westmount, Maplewood, and the older streets around Kinsmen Lake and 2nd Avenue, plus the commercial and light industrial strip along Highway 1 and Ridge Road." },
      { title: "Wheatland County", text: "Farms, acreages and yards along Highway 1, Highway 817, Highway 564 and Highway 24, including Carseland, Cheadle, Nightingale, Lyalta, Rockyford and Hussar, and the irrigation-district roads in between. Long gravel approaches and field access are routine; soft ground after irrigation or spring melt is the only limit." },
    ]},
    { eyebrow: "Four simple steps", title: "How It Works", cards: [{ title: "Describe it.", text: "Year, make, model, condition, and whether it's in town, on the farm or at a tow yard." }, { title: "Get a number the same day.", text: "Tow included." }, { title: "Book a window.", text: "Same day or next for Strathmore." }, { title: "Get paid.", text: "Bill of sale, cash or e-transfer, and it's loaded." }] },
    { eyebrow: "Ownership", title: "Alberta Paperwork", intro: ["Photo ID matching the registered owner and proof of ownership. We complete the bill of sale with you and leave you a copy.", "Your plate stays with you. Cancel or transfer the registration at a Strathmore registry or any Alberta registry agent, then call your insurer — on a farm vehicle that's been parked, there's often prepaid coverage to recover."] },
    { eyebrow: "Nearby", title: "Communities Near Strathmore", intro: ["Free towing also covers Chestermere, Irricana and Brooks, plus Calgary's east side and the county land between."] },
  ],
  faqs: [["Do you come out to Wheatland County farms?", "Yes, with no rural surcharge, including long approaches and field access."], ["Do you buy grain trucks?", "Regularly. They're heavy, which works in your favour."], ["Can you collect from a tow yard on Highway 1?", "Yes. Give us the address and release authorisation."], ["Do you buy insurance write-offs from highway collisions?", "Yes, including salvage and non-repairable status. Have the insurer's buyback paperwork ready."], ["How long to get to Strathmore?", "About forty-five minutes. Same-day pickup is often possible for morning calls."], ["How do you pay?", "Cash or e-transfer, before the vehicle moves."]],
  finalTitle: "Clear the Yard", finalText: "One truck or a whole fence line — one call gets you a number today.", finalCta: "Get a Free Offer",
};
export default function CashForCarsStrathmorePage() { return <ServicePage data={data} />; }
