import type { Metadata } from "next"; import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/lifted-white-suv-junk-car-calgary.jpeg"; import ranchImage from "@/assets/images/black-chevrolet-cash-car-sale-calgary.jpeg";
export const metadata: Metadata={title:"Cash for Junk Cars Nanton | Free Towing, Cash on Pickup",description:"Cash for junk cars in Nanton and area. We buy non-running, wind and hail-damaged and scrap vehicles, tow free from town and ranch, and pay on pickup.",alternates:{canonical:"https://www.junkacar.ca/cash-for-cars-nanton"},openGraph:{title:"Cash for Junk Cars Nanton | Free Towing, Cash on Pickup",description:"Cash for junk cars in Nanton and area. We buy non-running, wind and hail-damaged and scrap vehicles, tow free from town and ranch, and pay on pickup.",url:"https://www.junkacar.ca/cash-for-cars-nanton",type:"website",images:[{url:heroImage.src,alt:"Junk vehicle ready for free pickup in Nanton"}]}};
const data:ServicePageData={path:"/cash-for-cars-nanton",label:"Cash for Cars Nanton",h1:"Cash for Junk Cars in Nanton — Free Pickup in Wind Country",subhead:"We're about an hour and ten minutes north on the QEII. Ranch truck, town car or hail write-off, we'll give you a straight number the same day, tow it free, and pay you before it goes on the deck.",primaryCta:"Get My Cash Offer",heroImage,heroAlt:"White SUV ready for junk car pickup near Nanton",trustItems:["Free Nanton towing","Ranch pickup","Same-day offers","Paid at pickup"],sections:[
{eyebrow:"Wind country",title:"What Nanton's Wind Does to a Vehicle",intro:["Anyone who's opened a car door in Nanton in January knows the wind here is different. The stretch below the Porcupine Hills takes some of Alberta's strongest Chinook winds, and vehicles pay for it."],cards:[{title:"Doors, hinges and panels",text:"A door caught by a gust can bend a hinge, snap the check strap or fold into the fender. Over time doors sag, stop sealing and let in water and dust."},{title:"Sandblasted paint and pitted glass",text:"Wind carries grit, gravel dust and field soil, leaving dull paint, frosted-looking headlights and windshields covered in tiny pits."},{title:"Chinook freeze-thaw",text:"Rapid temperature swings repeatedly freeze moisture in seams, speeding rust in rockers, cab corners and brake lines."},{title:"Hail on the open prairie",text:"Summer storms roll across the flats unobstructed. Many hail write-offs here are mechanically perfect beneath the dents."}]},
{eyebrow:"Ranch country",title:"Ranch Trucks Under the Porcupine Hills",image:ranchImage,imageAlt:"Ranch vehicle ready for cash pickup near Nanton",intro:["Around Nanton the land is cattle ranches and mixed farms. Ranch trucks work gravel and pasture, pull stock trailers and haul feed, then stay beside the corrals or calving barn when retired.","These trucks are usually complete and heavy. A complete one-ton with a dead engine can carry more value than a running compact car."]},
{eyebrow:"Valuation",title:"What Nanton Junk Cars Are Worth",table:{headings:["Vehicle","Typical offer"],rows:[["Wind-worn older car, non-running","$250 – $800"],["Ranch half-ton, complete","$700 – $2,000"],["One-ton or diesel, complete","$1,000 – $3,500"],["Hail-damaged, mechanically sound","$1,500 – $8,000"],["Several vehicles, one ranch","Per-vehicle offer improves"]]},after:["Sagging doors, pitted paint and frosted headlights barely move our number — we're pricing weight, parts and the catalytic converter, not appearance."]},
{eyebrow:"One call handles it",title:"Our Services in Nanton",intro:["Town lot or ranch yard, every service covers Nanton and surrounding Willow Creek and Foothills County land."],cards:[{title:"Junk Car Removal in Nanton",text:<>Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> straps wind-bent doors, winches vehicles on and removes them from town or beside the corrals.</>},{title:"Scrap Car Removal in Nanton",text:<>Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> clears retired ranch trucks and captures old oils and coolant properly.</>},{title:"Cash for Scrap Cars in Nanton",text:<>Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> explains why weight and parts matter more than sandblasted paint.</>},{title:"Free Towing in Nanton",text:<><Link href="/free-towing-calgary">Free towing</Link> covers Nanton and nearby ranch country, including pasture access and multi-truck clear-outs.</>}]},
{eyebrow:"Local situations",title:"Nanton Situations We Handle",cards:[{title:"“The door won't close properly anymore.”",text:"We'll strap it shut for transport."},{title:"“It's out by the corrals.”",text:"Tell us about gates, cattle guards and ground conditions."},{title:"“It's registered to the ranch.”",text:"Workable with signing authority. Call first."},{title:"“It's a hail write-off in the driveway.”",text:"Have the insurer's buyback documents ready. These are among the best vehicles we buy."}]},
{eyebrow:"Selling locally",title:"Why Private Sales Are Hard in Nanton",intro:["In a small town there are few buyers for a rough vehicle, while posting to Calgary means strangers driving ninety minutes to negotiate.","For anything with wind damage, rust, hail dents or a dead drivetrain, a straight cash offer with free towing avoids ads, wasted weekends and uncertainty."]},
{eyebrow:"Coverage",title:"Where We Collect Around Nanton",intro:["The town of Nanton, including 20th Avenue, 19th Street and historic Main Street, plus ranches and acreages in the MD of Willow Creek and Foothills County along Highway 2, 533 and 527, including Parkland, Stavely, Cayley and toward Chain Lakes."]},
{eyebrow:"Simple sale",title:"How It Works",intro:["Describe the vehicle and access. You'll have a same-day number with towing included; pickup is usually next day. We complete the bill of sale, pay cash or e-transfer, and load.","Bring matching photo ID and proof of ownership. Keep your plate and cancel or transfer registration afterward."]},{eyebrow:"Nearby",title:"Communities Near Nanton",intro:["Free towing also covers High River, Okotoks and Lethbridge, plus the ranch country between."]}],faqs:[["Does wind damage lower the price?","Barely. Body and paint damage matter to private buyers, not weight and parts value."],["Do you come out to ranches?","Yes, with no rural surcharge."],["How far is Nanton for you?","About an hour and ten minutes. Pickups are usually next day."],["Do you buy hail write-offs?","Regularly, including salvage status."],["Any fees?","None — nothing deducted at pickup."],["Cash or e-transfer?","Either, before the vehicle moves."]],finalTitle:"Book a Nanton Pickup",finalText:"One call gets you a number today and a truck out tomorrow.",finalCta:"Get a Free Offer"};
export default function Page(){return <ServicePage data={data}/>}
