import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/silver-mercedes-garage-junk-car-sale-calgary.jpeg";
import winterImage from "@/assets/images/white-ford-escape-junk-car-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Didsbury | Free Towing, Paid on Pickup", description: "Cash for junk cars in Didsbury and Mountain View County. We buy farm trucks, non-runners and scrap vehicles, tow free, and pay you at pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-didsbury" }, openGraph: { title: "Cash for Junk Cars Didsbury | Free Towing, Paid on Pickup", description: "Cash for junk cars in Didsbury and Mountain View County. We buy farm trucks, non-runners and scrap vehicles, tow free, and pay you at pickup.", url: "https://www.junkacar.ca/cash-for-cars-didsbury", type: "website", images: [{ url: heroImage.src, alt: "Vehicle ready for cash pickup in Didsbury" }] } };

const data: ServicePageData = { path: "/cash-for-cars-didsbury", label: "Cash for Cars Didsbury", h1: "Cash for Junk Cars in Didsbury — Farm Trucks, Cars and Everything Between", subhead: "We're about an hour south of you on the QEII. If a vehicle got parked for the winter and never started again, we'll give you an honest number, tow it free, and pay you before it leaves the yard.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "Silver vehicle ready for junk car sale and pickup near Didsbury", trustItems: ["Free Didsbury towing", "Mountain View County", "Same-day offers", "Paid at pickup"], sections: [
  { eyebrow: "The seasonal cycle", title: "Parked for Winter, Never Started Again", image: winterImage, imageAlt: "Non-running vehicle awaiting pickup after winter near Didsbury", intro: ["Farm country runs on seasons, and so do farm vehicles. Around Didsbury, many trucks work flat out from seeding through harvest and then get parked when snow comes. Most start again in April. Some don't — and those are the ones we hear about."], cards: [
    { title: "What a winter of sitting does", text: <>Batteries drain and freeze, fuel degrades and gums lines, brakes seize, tires flat-spot, and seals dry out. Mice move into the air box, heater housing and wiring almost immediately. A truck that was tired but running in October can be a non-runner by April.</> },
    { title: "The truck that gets demoted", text: "On many farms a vehicle becomes the yard truck, then the parts truck. At each step it moves further from the house and gets less attention until it's simply part of the scenery behind the bins." },
    { title: "Why spring is the right time to decide", text: "If it didn't make it through winter, get a number now and book pickup for when the yard firms up. The decision is made and the truck is gone before seeding keeps everyone too busy." },
  ]},
  { eyebrow: "Town vehicles", title: "In Town, It's a Different Story", intro: ["Didsbury has many long-owned cars that simply stopped being needed — a licence not renewed, a move to a smaller home, or a spouse's car nobody drives. These are usually complete, often garage-kept, and less rusty than the regional average, which works in your favour.", "Often the person selling isn't the person who drove the car, and paperwork may need sorting. We'll walk you through it without rushing."] },
  { eyebrow: "Valuation", title: "What Didsbury Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Garage-kept town car, non-running", "$400 – $1,800"], ["Farm half-ton that didn't survive winter", "$600 – $1,800"], ["Grain truck or one-ton, complete", "$900 – $3,000"], ["Parts truck, partly stripped", "$200 – $600"], ["Several vehicles, one yard", "Per-vehicle offer improves"]] }, after: ["Weight sets the floor. Completeness and salvageable parts push it up; rodent damage and missing components pull it down. The catalytic converter is priced separately and on a heavier truck can be a large share of the offer."] },
  { eyebrow: "One call handles it", title: "Our Services in Didsbury", intro: ["Farm yard or town garage, each service covers Didsbury and surrounding Mountain View County — with free towing and payment when we collect."], cards: [
    { title: "Junk Car Removal in Didsbury", text: <>Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> winches winter non-runners out as-is, and we&apos;ll book pickup for when your yard is firm enough for a loaded truck.</> },
    { title: "Scrap Car Removal in Didsbury", text: <>Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> clears retired farm and parts trucks around Didsbury, Carstairs and Cremona, capturing old fuel, oils and antifreeze.</> },
    { title: "Cash for Scrap Cars in Didsbury", text: <>Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> explains how weight, completeness, rodent damage and the catalytic converter move the number.</> },
    { title: "Free Towing in Didsbury", text: <><Link href="/free-towing-calgary">Free towing</Link> is included with every Didsbury offer, including Mountain View County range roads and bookings held until spring ground dries.</> },
  ]},
  { eyebrow: "Local situations", title: "Didsbury Situations We Handle", cards: [{ title: "“It won't start after winter.”", text: "Normal. We winch it on — no boost, no keys needed." }, { title: "“The yard is still too soft.”", text: "Get your number now and book for when it firms up. We'd rather wait a week than rut your yard." }, { title: "“It's registered to the farm.”", text: "Workable with signing authority for the farm corporation or partnership. Call first." }, { title: "“It was my late husband's car.”", text: "Documentation showing authority over the estate is needed, and we'll tell you exactly what before anyone drives out." }] },
  { eyebrow: "Repair or sell", title: "Is It Worth Getting It Running Again?", intro: ["Sometimes a vehicle that won't start after winter just needs a battery. Before you sell, it's worth trying a new battery and fresh fuel — if it runs cleanly, it may be worth more as a working farm truck than to us.", "If it still won't run, or it runs with a knock, slipping transmission or burning-coolant smell, the problem is bigger. Get our number, compare it with the shop's estimate, and decide from there."] },
  { eyebrow: "Coverage", title: "Where We Collect Around Didsbury", intro: ["The town of Didsbury, including streets around Main Street and 20th Avenue and newer developments on the west side, plus Mountain View County farms and acreages along Highway 2, Highway 2A and Highway 582, including Carstairs, Westcott, Cremona and toward Sundre and Olds."] },
  { eyebrow: "Simple sale", title: "How It Works", intro: ["Describe the vehicle and where it sits. We return a same-day number with the tow included. Pickup is typically next day for Didsbury. On site we complete the bill of sale, pay by cash or e-transfer, and load.", "Bring photo ID matching the registered owner and proof of ownership. Keep your plate, cancel or transfer the registration, and ask your insurer about prepaid coverage on a vehicle that sat all winter."] },
  { eyebrow: "Nearby", title: "Communities Near Didsbury", intro: ["Free towing also covers Olds, Airdrie and Cochrane, plus the Mountain View County land between."] },
], faqs: [["Why won't my truck start after sitting all winter?", "Usually a frozen, discharged battery, stale fuel, seized brakes or rodent-damaged wiring — often several at once."], ["Is it worth fixing or selling?", "If the repair quote is higher than the truck's value, selling usually makes sense. Our number gives you something firm to compare."], ["Do you come to Mountain View County farms?", "Yes, with no rural surcharge."], ["How long to get to Didsbury?", "Around an hour. Pickup is usually next day."], ["Any fees?", "None."], ["Cash or e-transfer?", "Either, before the vehicle moves."]], finalTitle: "Get a Number Before Seeding", finalText: "Call now, book pickup for when the ground is ready, and have it gone before the busy season.", finalCta: "Get a Free Offer" };
export default function CashForCarsDidsburyPage() { return <ServicePage data={data} />; }
