import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/black-chevrolet-cash-car-sale-calgary.jpeg";
import ranchImage from "@/assets/images/white-hyundai-sale-paperwork-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Okotoks | Free Towing, Same-Day Cash", description: "Cash for junk cars in Okotoks and Foothills County. We buy non-running, damaged and scrap vehicles, tow free from town or acreage, and pay on pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-okotoks" }, openGraph: { title: "Cash for Junk Cars Okotoks | Free Towing, Same-Day Cash", description: "Cash for junk cars in Okotoks and Foothills County. We buy non-running, damaged and scrap vehicles, tow free from town or acreage, and pay on pickup.", url: "https://www.junkacar.ca/cash-for-cars-okotoks", type: "website", images: [{ url: heroImage.src, alt: "Vehicle ready for cash pickup in Okotoks" }] } };

const data: ServicePageData = {
  path: "/cash-for-cars-okotoks", label: "Cash for Cars Okotoks", h1: "Cash for Junk Cars in Okotoks — Town or Foothills County, Free Pickup",
  subhead: "We're about forty minutes north of you. A commuter car that's finally given up, a ranch truck that's been parked since the last calving season, or a hail write-off in the driveway — we'll give you a real number the same day, tow it free, and pay you before it leaves.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "Black Chevrolet ready for a cash car offer in Okotoks", trustItems: ["Free Okotoks towing", "Foothills County covered", "Same-day offers", "Cash at pickup"],
  sections: [
    { eyebrow: "Two kinds of vehicle", title: "Okotoks Wears Out Vehicles in Two Different Ways", intro: ["Most of our Okotoks calls fall into one of two groups, and they could hardly be more different — in how they got here, and in what they're worth."], cards: [
      { title: "The south Calgary commuter", text: <>A big share of Okotoks drives north every weekday — up Highway 2 or the 2A, onto Macleod Trail or Deerfoot, and into south Calgary or downtown. It&apos;s roughly ninety kilometres round trip, much of it at highway speed and a fair bit of it in slow traffic at the city edge around Seton and Shawnessy.<br /><br />After six or seven years of that, a commuter vehicle has high kilometres, a worn clutch or tired transmission, and five winters of brine working into the rockers and brake lines. It usually still runs. It&apos;s just crossed the point where a dealer offers almost nothing and a repair shop quotes more than it&apos;s worth.</> },
      { title: "The Foothills County working truck", text: <>Past the town boundary, Foothills County is still ranch and acreage country — west toward Millarville and Priddis, south toward the Highwood, east toward De Winton and Aldersyde. Trucks here haul feed, pull stock trailers and run gravel roads, and when they&apos;re retired they tend to stay on the property.<br /><br />These trucks are often low on kilometres but hard on their drivetrains, and they&apos;re usually complete. That makes them heavier and more parts-rich than a commuter car — and generally worth more to us, even when they haven&apos;t moved in years.</> },
      { title: "A town with a mature core", text: "Okotoks also has an older heart — the Olde Towne streets around Elizabeth Street and McRae Street, with detached garages, narrow lanes and long-owned vehicles tucked out of sight. Those pickups are straightforward, just a little tighter than the newer subdivisions on the edges of town." },
      { title: "Hail along the foothills edge", text: "Summer storms build over the foothills and track straight across the Sheep River valley. Okotoks sees its share of hail, and a mechanically sound SUV with a dented roof is one of the best vehicles we buy, because we price what's underneath the paint." },
    ]},
    { eyebrow: "Valuation", title: "What Okotoks Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["High-kilometre commuter car, still running", "$800 – $3,500"], ["Older car or SUV, non-running", "$300 – $1,200"], ["Ranch half-ton, parked but complete", "$700 – $2,000"], ["3/4-ton or one-ton, complete", "$1,000 – $3,500"], ["Hail-damaged, mechanically sound", "$1,500 – $8,000"], ["Several vehicles on one property", "Per-vehicle offer improves"]] }, after: ["Weight sets the floor, and ranch trucks carry more of it. Salvageable components — engines, transmissions, axles, boxes and tailgates — push the number up. The catalytic converter is priced separately, and on a heavy truck it's often a large part of the offer. If yours has been cut off, tell us upfront and the number will be right the first time.", "For the commuter car, mileage barely matters to us. It matters enormously to a dealer. That's the whole reason a high-kilometre Okotoks commuter often gets a better number here than on a trade-in."] },
    { eyebrow: "One call handles it", title: "Our Services in Okotoks", intro: ["Whether it's a worn-out commuter in town or a ranch truck out in the county, one of these covers it — each with free towing and payment when we collect."], cards: [
      { title: "Junk Car Removal in Okotoks", text: <>The commuter car that&apos;s quit after years on Highway 2 and Macleod is our most common in-town call, whether it&apos;s in a D&apos;Arcy driveway or an Olde Towne garage off the lane. Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> handles tight lanes and detached garages as easily as open driveways, and it&apos;s usually same day.</> },
      { title: "Scrap Car Removal in Okotoks", text: <>Out in Foothills County, retired trucks often sit behind a quonset for years before anyone decides they&apos;re scrap. Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> collects them from ranch yards toward Millarville, Priddis and De Winton and processes them properly — fluids captured, parts recovered, nothing left to leak toward the Sheep River.</> },
      { title: "Cash for Scrap Cars in Okotoks", text: <>A complete, low-kilometre ranch truck is heavier and more parts-rich than most people assume. Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> explains how curb weight, drivetrain parts and the catalytic converter combine — and why a parked Foothills County truck often out-values a running commuter sedan.</> },
      { title: "Free Towing in Okotoks", text: <>From Olde Towne to a quarter section off Highway 7, collection costs nothing. <Link href="/free-towing-calgary">Free towing</Link> is built into every Okotoks offer, including long approaches, pasture access and multi-vehicle ranch clear-outs.</> },
    ]},
    { eyebrow: "Local situations", title: "Common Okotoks Situations, Sorted", cards: [
      { title: "“It still runs, but the repair quote is more than it's worth.”", text: "That's the classic commuter-car moment. Get our number and put it beside the repair quote. If the repair is more than half of what the car would be worth fixed, selling is almost always the better call." },
      { title: "“It's been parked in the quonset for six years.”", text: "Normal. Flat tires, seized brakes, a mouse nest in the air box — we see it weekly. We bring skates and a winch, and you don't need to find the keys." },
      { title: "“There's a row of them along the fence.”", text: "Describe what you can and we'll quote the lot. One or two visits, one payment, and a better per-vehicle number than selling them separately." },
      { title: "“It's registered to the ranch.”", text: "Farm corporation and family partnership registrations are workable with the right signing authority. Call first so the paperwork is ready." },
      { title: "“It's in an Olde Towne garage off the lane.”", text: "Tight but routine. A photo of the lane and the garage door helps us bring the right truck." },
    ]},
    { eyebrow: "Compare the numbers", title: "Trading It In at the Dealer vs Selling It to Us", image: ranchImage, imageAlt: "Vehicle owner completing a cash car sale near Okotoks", intro: ["Okotoks has plenty of dealerships along Southridge Drive and Highway 2A, and a trade-in is the obvious first thought. For a clean, late-model vehicle, it often makes sense.", "For anything older, high-kilometre, rusted or not running, the maths changes. Dealers price trade-ins on how easily they can resell the vehicle on their own lot. A 220,000-km commuter with a rough transmission is a vehicle they don't want, so the trade number is low — and it's credit toward another purchase, not cash.", "We price on weight, parts and material. None of those care about kilometres or cosmetics. So get both numbers: if the trade-in is higher, take it. If it isn't, you've got cash in hand and no obligation to buy anything."] },
    { eyebrow: "Coverage", title: "Where We Collect Around Okotoks", cards: [
      { title: "In town", text: "D'Arcy, Drake Landing, Cimarron, Crystal Shores, Crystal Ridge, Air Ranch, Sheep River Ridge, Westmount, Mountainview, Tower Hill, Suntree, Wedderburn, Sandstone, Rosemont, Hunters Glen, Olde Towne, and the commercial strip along Southridge Drive and Northridge Drive." },
      { title: "Foothills County", text: "Ranches, acreages and country residential along Highway 7, Highway 2A, Highway 552 and Highway 549, including De Winton, Aldersyde, Millarville, Priddis and the land along the Sheep River. Long approaches, pasture access and vehicles behind barns are all routine." },
    ]},
    { eyebrow: "Four simple steps", title: "From Quote to Cash", cards: [{ title: "Tell us about it.", text: "Year, make, model, condition, and whether it's in town or out on the county." }, { title: "Get your number.", text: "Same day, with the tow included and nothing deducted later." }, { title: "Book a window.", text: "Same day or next for Okotoks." }, { title: "Get paid.", text: "Bill of sale, cash or e-transfer, and it's loaded. About twenty minutes." }] },
    { eyebrow: "Paperwork", title: "Paperwork for Okotoks Sellers", intro: ["Photo ID matching the registered owner and proof of ownership. We complete the bill of sale on site and leave you a copy.", "Keep your plate — it belongs to you in Alberta. Afterward, cancel or transfer the registration at an Okotoks registry or any Alberta registry agent, and ask your insurer about unused prepaid coverage."] },
    { eyebrow: "Nearby", title: "Communities Near Okotoks", intro: ["Free towing also covers High River, Diamond Valley and Nanton, plus south Calgary and the Foothills County land between them."] },
  ],
  faqs: [["Do you pick up from Foothills County acreages?", "Yes, at no extra charge, including long gravel approaches and pasture access."], ["My commuter car still runs. Should I trade it in instead?", "Get both numbers. On a high-kilometre vehicle, ours is often better because mileage barely affects weight and parts value."], ["How long to get to Okotoks?", "Around forty minutes. Same-day pickup is common for morning calls."], ["Can you take several trucks from one ranch?", "Yes, and it improves the per-vehicle offer."], ["Is there a fee if the vehicle is worth very little?", "Never. The tow is still free and the offer never goes negative."], ["Cash or e-transfer?", "Either, before the vehicle moves."]],
  finalTitle: "Book Your Okotoks Pickup", finalText: "Town driveway or county quarter section — one call gets you a number today and a truck out tomorrow at the latest.", finalCta: "Get a Free Offer",
};
export default function CashForCarsOkotoksPage() { return <ServicePage data={data} />; }
