import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/black-chevrolet-cash-car-sale-calgary.jpeg";
import serviceImage from "@/assets/images/white-hyundai-sale-paperwork-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Diamond Valley | Black Diamond & Turner Valley", description: "Cash for junk cars in Diamond Valley — Black Diamond and Turner Valley. We buy non-running, scrap and damaged vehicles, tow free, and pay at pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-diamond-valley" }, openGraph: { title: "Cash for Junk Cars Diamond Valley | Black Diamond & Turner Valley", description: "Cash for junk cars in Diamond Valley — Black Diamond and Turner Valley. We buy non-running, scrap and damaged vehicles, tow free, and pay at pickup.", url: "https://www.junkacar.ca/cash-for-cars-diamond-valley", type: "website", images: [{ url: heroImage.src, alt: "Vehicle ready for cash pickup in Diamond Valley" }] } };

const data: ServicePageData = { path: "/cash-for-cars-diamond-valley", label: "Cash for Cars Diamond Valley", h1: "Cash for Junk Cars in Diamond Valley — Black Diamond and Turner Valley", subhead: "We're about fifty minutes northeast of you, where the foothills start. Whether your address still says Black Diamond or Turner Valley, we'll give you a real number the same day, tow the vehicle free, and pay you before it leaves.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "Black Chevrolet ready for a cash car offer in Diamond Valley", trustItems: ["Black Diamond covered", "Turner Valley covered", "Free foothills towing", "Paid at pickup"], sections: [
  { eyebrow: "One town, three names", title: "Black Diamond, Turner Valley and Diamond Valley — We Cover All of It", intro: ["In 2023 the towns of Black Diamond and Turner Valley amalgamated into one municipality, the Town of Diamond Valley. Most residents still use the old names day to day, and plenty of registrations, insurance papers and old bills of sale still carry them.", "None of that changes anything when you sell a vehicle. Your registration is valid under the name it was issued with, the address on your ID doesn't need updating first, and we collect from both sides of the Sheep River equally."] },
  { eyebrow: "Why Diamond Valley", title: "What the Foothills Do to Vehicles Here", cards: [
    { title: "Oil-patch roots", text: <>Turner Valley is where Alberta&apos;s oil and gas industry began, and service trucks, older crew cabs, welding rigs and work units still turn up here. Heavy work trucks are among the better-paying non-runners: they carry a lot of steel and their drivetrain components remain in demand.</> },
    { title: "Foothills weather", text: "Sharper Chinook swings and heavier snow push moisture into seams, accelerate rust, and leave more vehicles buried, stuck or parked for the season and never restarted." },
    { title: "The Cowboy Trail and gravel", text: "Highway 22 runs through town, and ranch roads toward Millarville, Longview and Kananaskis are gravel. Washboard, dust and stone chips wear suspension components and undercarriages." },
    { title: "The long commute", text: "Many residents drive into Calgary daily — well over a hundred kilometres round trip. Vehicles reach high kilometres fast, and major repairs eventually stop making financial sense." },
  ]},
  { eyebrow: "Valuation", title: "What Diamond Valley Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Older car, non-running, complete", "$250 – $800"], ["High-kilometre commuter, running", "$900 – $4,000"], ["Ranch half-ton, non-running", "$700 – $2,000"], ["Service truck, welding rig or one-ton", "$1,000 – $3,500"], ["Hail-damaged, mechanically sound", "$1,500 – $8,000"]] }, after: ["Weight sets the floor — a steel service body or flatdeck adds a lot of it. Salvageable parts push the number up, and the catalytic converter is priced separately. Rust pulls it down. The year, make and model are enough for us to start."] },
  { eyebrow: "One call handles it", title: "Our Services in Diamond Valley", intro: ["Black Diamond side or Turner Valley side, town lot or foothills ranch — every service covers all of Diamond Valley, with free towing and payment on collection."], cards: [
    { title: "Junk Car Removal in Diamond Valley", text: <>Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> brings the winch and correct truck for buried vehicles, steep west-side lanes and difficult foothills access.</> },
    { title: "Scrap Car Removal in Diamond Valley", text: <>Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> clears retired oil-patch and ranch trucks and captures diesel, hydraulic fluid and oils rather than leaving them near the Sheep River.</> },
    { title: "Cash for Scrap Cars in Diamond Valley", text: <>Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> shows how a service body, drivetrain and catalytic converter combine to give retired work trucks real value.</> },
    { title: "Free Towing in Diamond Valley", text: <><Link href="/free-towing-calgary">Free towing</Link> covers both sides of town and surrounding Foothills County ranches, whichever town name is on your paperwork.</> },
  ]},
  { eyebrow: "Local situations", title: "Situations We Handle in Diamond Valley", cards: [{ title: "“My registration still says Turner Valley.”", text: "Not a problem. It doesn't need updating before you sell." }, { title: "“It's a work truck from a company that closed.”", text: "Workable with documentation showing signing authority or the company's dissolution. Call first so we can tell you what's needed." }, { title: "“It's snowed in on the property.”", text: "Clearing a rough path helps. If it's truly buried, we'll book after a thaw rather than force it." }, { title: "“It's up a steep lane on the west side.”", text: "Tell us the grade and access. We'll bring the right truck and set up for a controlled winch pull." }] },
  { eyebrow: "Work vehicles", title: "Selling a Retired Oilfield or Service Truck", image: serviceImage, imageAlt: "Retired work vehicle being documented for sale in Diamond Valley", intro: ["Service trucks sell differently from ordinary pickups. A steel service body, crane, welder deck or toolboxes makes the truck much heavier, and that extra steel is worth money.", "Equipment such as a welder, compressor or crane may have more value sold separately. Tell us what still works and we'll either price it in or suggest selling it separately, whichever gets you more.", "Company-registered trucks need someone with signing authority. If the company has wound down, documentation of that is usually enough."] },
  { eyebrow: "Coverage", title: "Where We Collect", cards: [{ title: "Black Diamond side", text: "Downtown Black Diamond, Crestview, Eagle Ridge, Sunset Ridge, Southridge, and streets along Highway 22 and Centre Avenue." }, { title: "Turner Valley side", text: "Main Street Turner Valley, the Royalite area, Decalta, Flare 'n Derrick, Westridge, and older streets along Sunset Boulevard and the Sheep River." }, { title: "Foothills County around town", text: "Ranches and acreages along Highway 22, Highway 7 and Highway 546, including Millarville, Longview, Priddis and toward Kananaskis." }] },
  { eyebrow: "Simple sale", title: "How It Works", intro: ["Describe the vehicle, get a same-day number with the tow included, and pick a window — usually next day for Diamond Valley. On site we complete the bill of sale, pay cash or e-transfer, and load.", "You'll need photo ID matching the registered owner and proof of ownership. Keep your plate, then cancel or transfer the registration and ask your insurer about unused prepaid coverage."] },
  { eyebrow: "Nearby", title: "Communities Near Diamond Valley", intro: ["Free towing also covers Okotoks, High River and Bragg Creek, plus the Foothills County land between."] },
], faqs: [["Do you still serve Black Diamond and Turner Valley?", "Yes — both are part of Diamond Valley now, and we collect from every part of it."], ["Do I need to update my address before selling?", "No. The old town name on your registration or ID is fine."], ["Do you buy old oilfield service trucks?", "Regularly. They're heavy and parts-rich, and usually near the top of our non-running range."], ["How long to get there?", "About fifty minutes. Next-day pickup is typical."], ["Any fee?", "None. No mileage charge, nothing deducted at pickup."], ["Cash or e-transfer?", "Either, before the vehicle moves."]], finalTitle: "Book a Diamond Valley Pickup", finalText: "Whatever the address says, one call gets you a number today.", finalCta: "Get a Free Offer" };
export default function CashForCarsDiamondValleyPage() { return <ServicePage data={data} />; }
