import type {Metadata} from "next"; import Link from "next/link"; import {ServicePage,type ServicePageData} from "@/components/service-page"; import hero from "@/assets/images/white-hyundai-sale-paperwork-calgary.jpeg"; import recycle from "@/assets/images/black-chevrolet-cash-car-sale-calgary.jpeg";
export const metadata:Metadata={title:"About Us | Buying Vehicles Across Alberta Since 1998",description:"Buying vehicles across Alberta since 1998 — over 500 a month, paid on the spot, AMVIC compliant. Serving Calgary and 19 communities across the province.",alternates:{canonical:"https://www.junkacar.ca/about"}};
const data:ServicePageData={path:"/about",label:"About Us",h1:"About Us",subhead:"Buying vehicles across Alberta since 1998 — straightforward offers, free collection and payment when we pick up.",primaryCta:"Get a Free Offer",heroImage:hero,heroAlt:"Vehicle owner completing sale paperwork with Junk A Car",trustItems:["Since 1998","500+ vehicles monthly","AMVIC licensed company","Paid at collection"],sections:[
{eyebrow:"Our history",title:"Twenty-Eight Years of Buying Vehicles in Alberta",intro:["We started buying vehicles in 1998. We've watched scrap prices, emissions rules, vehicle choices and selling methods change several times.","What hasn't changed is the job. Somebody has a vehicle they don't want. We work out what it's worth, tell them, and if they agree we collect it and pay them.","Today we buy more than five hundred vehicles a month across Alberta. This site covers Calgary, Rocky View and Foothills County, and nineteen communities from Airdrie to Medicine Hat."]},
{eyebrow:"Experience at scale",title:"What Buying 500 Vehicles a Month Actually Does for You",cards:[{title:"We already know what your vehicle is worth",text:"Buying roughly six thousand vehicles a year gives us current knowledge of parts demand, converters and actual returns. Quotes arrive quickly and remain stable."},{title:"The tow is genuinely covered",text:"Regular routing makes city, acreage and long-distance collection workable without mileage, rural or minimum-value charges."},{title:"You're paid the day we collect",text:"Choose cash or e-transfer before the vehicle moves — never a cheque later or payment after processing."}]},
{eyebrow:"Accountability",title:"Licensed and AMVIC Compliant",intro:["We are an AMVIC licensed company. Licensing makes vehicle buyers accountable for the transaction, paperwork and what happens afterward.","In practice, the bill of sale is completed properly, the transaction is documented, and a provincial regulator exists if something goes wrong."]},
{eyebrow:"Transparent valuation",title:"How We Price, and Why the Number Doesn't Move",cards:[{title:"What goes into the number",text:<>Curb weight, non-ferrous metal, the catalytic converter and reusable parts determine value. Rust lowers it and completeness raises it. See the full arithmetic on our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link>.</>},{title:"What we ask in return",text:"Describe missing converters, engines, transmissions and true condition honestly. None stops the sale; all affect price. Upfront information keeps the first number accurate."}]},
{eyebrow:"Local knowledge",title:"Why Calgary Keeps Us Busy",lists:[{items:["Hail writes off mechanically healthy vehicles throughout Calgary's storm corridor.","Road brine and Chinook freeze-thaw cycles accelerate rust in rockers, lines and frames.","Long commuter distances produce high-kilometre vehicles dealers no longer want."]}]},
{eyebrow:"Responsible processing",title:"What Happens to the Vehicles",image:recycle,imageAlt:"Vehicle prepared for responsible dismantling and recycling in Calgary",intro:["Fluids and refrigerant are recovered first. Batteries, tires and mercury switches enter separate streams. Reusable parts are inventoried, then remaining ferrous and non-ferrous metals are recycled.","At five hundred vehicles a month, that keeps substantial material out of ground draining toward the Bow and Elbow."]},
{eyebrow:"Coverage",title:"Where We Work",intro:["Every Calgary quadrant, industrial areas, Rocky View County, Springbank and Foothills County.","Free collection also reaches Airdrie, Chestermere, Cochrane, Okotoks, Bragg Creek, Strathmore, High River, Irricana, Diamond Valley, Didsbury, Nanton, Canmore, Banff, Olds, Red Deer, Ponoka, Brooks, Lethbridge and Medicine Hat."]}],faqs:[],finalTitle:"Get in Touch",finalText:"Call (403) 688-7307 or send the details through the form. We'll come back the same day with a number.",finalCta:"Get a Free Offer"};export default function Page(){return <ServicePage data={data}/>}
