import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/white-ford-escape-junk-car-calgary.jpeg";
import waterImage from "@/assets/images/blue-mini-countryman-driveway-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars High River | Free Towing, Paid on Pickup", description: "Cash for junk cars in High River. We buy non-running, water-damaged, hail-damaged and scrap vehicles, tow free across town and county, and pay at pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-high-river" }, openGraph: { title: "Cash for Junk Cars High River | Free Towing, Paid on Pickup", description: "Cash for junk cars in High River. We buy non-running, water-damaged, hail-damaged and scrap vehicles, tow free across town and county, and pay at pickup.", url: "https://www.junkacar.ca/cash-for-cars-high-river", type: "website", images: [{ url: heroImage.src, alt: "Junk vehicle ready for free pickup in High River" }] } };

const data: ServicePageData = { path: "/cash-for-cars-high-river", label: "Cash for Cars High River", h1: "Cash for Junk Cars in High River — Free Pickup, Honest Numbers", subhead: "We're about fifty minutes north on the QEII. Whatever state the vehicle is in — seized, rusted, hail-dented or water-damaged — we'll give you a straight number, tow it free, and pay you before it leaves.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "White SUV ready for junk car pickup in High River", trustItems: ["Free High River towing", "Foothills County covered", "Honest same-day offers", "Paid at pickup"], sections: [
  { eyebrow: "Water damage", title: "High River Understands Water Damage Better Than Anyone", image: waterImage, imageAlt: "Vehicle being assessed for hidden water damage in High River", intro: ["After June 2013, almost everyone in this town knows what floodwater does to a house. Fewer people realise how differently it affects a vehicle — or how long the damage keeps surfacing after everything looks dry."], cards: [
    { title: "Why water is worse than it looks", text: <>A vehicle that&apos;s sat in water may dry out, start, and even drive for a while. The problems show up later. Water gets into wiring harnesses, connectors and control modules and causes corrosion that surfaces months afterward as random electrical faults.<br /><br />It soaks into seat motors, carpet padding and sound insulation and never fully leaves. If the water rose high enough, it contaminates engine oil, transmission fluid and differential fluid. That&apos;s why a flood vehicle is worth less than a collision vehicle with the same visible damage.</> },
    { title: "Not only floods", text: "Basement garages that take on water during spring melt, vehicles parked in low spots during heavy summer rain, and cars left with a window or sunroof open through a storm all produce the same hidden damage on a smaller scale." },
    { title: "We buy them — and we ask you to tell us", text: "We buy water-damaged vehicles regularly. A water history lowers the number, but it doesn't stop the sale. Tell us upfront so the quote is accurate and stays accurate on pickup day." },
  ]},
  { eyebrow: "What to look for", title: "Signs a Vehicle Has Been in Water", intro: ["If you bought a used vehicle and you're not sure of its history, look for several of these signs. Mention anything you find when you call and we'll assess it honestly on arrival."], lists: [{ items: ["A musty or mildew smell that returns after cleaning", "A tide line or staining on door panels, seat bases or the trunk liner", "Rust on seat rails, seat bolts or metal under the dashboard", "Silt, sand or grit in the spare-tire well or under the carpet", "Fogging inside headlights or tail lights", "Electrical faults that come and go"] }] },
  { eyebrow: "Beyond water damage", title: "The Other High River Vehicles We Buy", cards: [
    { title: "Shift-work commuters", text: "The meat-processing plant north of town runs around the clock. Cold starts on a fixed schedule and short-then-highway driving wear engines, batteries and starters faster than ordinary daytime use." },
    { title: "Calgary commuters", text: "Others drive the QEII north every day — well over a hundred kilometres round trip. High kilometres and highway salt arrive together, and by year seven most commuter cars are worth far more to us than to a dealer." },
    { title: "Ranch trucks along the Highwood", text: "Foothills County around High River is cattle country. Ranch trucks work gravel and pasture, pull stock trailers, and stay on the property long after they're retired — usually complete, heavy and worth more than expected." },
  ]},
  { eyebrow: "Valuation", title: "What High River Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Water or flood-damaged vehicle", "$200 – $1,200"], ["Older car, non-running, dry and complete", "$300 – $900"], ["High-kilometre commuter, still running", "$900 – $4,000"], ["Ranch half-ton or one-ton, complete", "$800 – $3,000"], ["Hail-damaged, mechanically sound", "$1,500 – $8,000"]] }, after: ["Weight sets the floor. Salvageable parts raise it — and this is exactly where water damage costs you, because electronics and interiors that sat in water usually can't be resold. The catalytic converter and the metal itself are unaffected by water, which is why a flood vehicle is still worth something."] },
  { eyebrow: "One call handles it", title: "Our Services in High River", intro: ["Water-damaged, worn out or long parked — each service covers High River and surrounding Foothills County, with free towing and payment before the vehicle leaves."], cards: [
    { title: "Junk Car Removal in High River", text: <>Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> takes water-damaged and non-running vehicles from anywhere in town — Wallaceville to Emerson Lake — and gives you an honest number up front.</> },
    { title: "Scrap Car Removal in High River", text: <>Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> drains contaminated oil, coolant and fuel properly before processing, keeping it out of ground that drains toward the Highwood River.</> },
    { title: "Cash for Scrap Cars in High River", text: <>Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> explains why steel, aluminium and the catalytic converter still give a flood-damaged vehicle real value.</> },
    { title: "Free Towing in High River", text: <><Link href="/free-towing-calgary">Free towing</Link> is included with every High River offer, including ranches past Blackie or Cayley, gravel approaches and vehicles that won&apos;t roll.</> },
  ]},
  { eyebrow: "Common calls", title: "Common High River Situations", cards: [{ title: "“Insurance paid out and I kept the car.”", text: "That's a buyback. Have the insurer's paperwork ready. Salvage and non-repairable status both sell." }, { title: "“It won't start after sitting through winter.”", text: "Normal. We winch it on — no boost or keys needed." }, { title: "“It's on a ranch west of town.”", text: "Long gravel approaches are routine. Tell us the access and ground conditions." }] },
  { eyebrow: "Coverage", title: "Where We Collect Around High River", intro: ["Every part of town — Wallaceville, Sunrise, Hampton Hills, Montrose, Emerson Lake, Sunshine Meadows, Heritage Heights, Spitzee, Beachwood, Downtown and the older neighbourhoods along the Highwood River — plus the commercial strip on 12th Avenue and Centre Street.", "Beyond town, Foothills County ranches and acreages along Highway 2, Highway 23, Highway 543 and Highway 547, including Aldersyde, Cayley, Blackie and the land toward Longview."] },
  { eyebrow: "Simple sale", title: "How It Works", intro: ["Describe the vehicle honestly, including any water history. We come back the same day with a number that includes the tow, and pickup is usually same day or next. On site we complete the bill of sale with you, pay by cash or e-transfer, and load.", "Bring photo ID matching the registered owner and proof of ownership. Keep your plate, then cancel or transfer the registration at any registry agent and check with your insurer about unused prepaid coverage."] },
  { eyebrow: "Nearby", title: "Communities Near High River", intro: ["Free towing also covers Okotoks, Nanton and Diamond Valley, plus the Foothills County land between them."] },
], faqs: [["Do you buy flood-damaged vehicles?", "Yes. Water damage lowers the offer, but the metal and catalytic converter value remain."], ["Why is a flood car worth less than a crashed one?", "Because water ruins the electronics and interior — the parts that would otherwise be resold."], ["Do you pick up from Foothills County ranches?", "Yes, at no extra charge."], ["How long to get to High River?", "About fifty minutes. Same-day or next-day pickup is normal."], ["Is there any fee?", "None. Nothing is deducted at pickup."], ["Cash or e-transfer?", "Either, before the vehicle moves."]], finalTitle: "Get an Honest Number Today", finalText: "Tell us what you know about the vehicle, water history included. We'll tell you exactly what it's worth.", finalCta: "Get a Free Offer" };
export default function CashForCarsHighRiverPage() { return <ServicePage data={data} />; }
