import Image, { type StaticImageData } from "next/image";
import Link from "next/link";
import {
  ArrowDownRight, ArrowRight, BadgeDollarSign, Car, Check, ChevronDown, ChevronRight,
  CircleDollarSign, Clock3, FileCheck2, HandCoins, MapPin, Menu, Phone, Recycle,
  ShieldCheck, Snowflake, Sparkles, Truck, TriangleAlert, Zap,
} from "lucide-react";
import logo from "@/assets/junkacar-logo.png";
import heroPhoto from "@/assets/images/lifted-white-suv-junk-car-calgary.jpeg";
import trailerPhoto from "@/assets/images/damaged-ford-fiesta-trailer-pickup-calgary.jpeg";
import paperworkPhoto from "@/assets/images/silver-mercedes-garage-junk-car-sale-calgary.jpeg";
import drivewayPhoto from "@/assets/images/black-chevrolet-cash-car-sale-calgary.jpeg";
import sedanPhoto from "@/assets/images/silver-saturn-used-car-calgary.jpeg";
import signingPhoto from "@/assets/images/white-hyundai-sale-paperwork-calgary.jpeg";
import suvPhoto from "@/assets/images/white-ford-escape-junk-car-calgary.jpeg";
import { QuoteForm } from "@/components/quote-form";
import { JsonLd } from "@/components/seo-schema";

const phoneDisplay = "(403) 688-7307";
const phoneHref = "tel:+14036887307";

const payoutRanges = [
  ["Scrap only", "Stripped, rusted through, missing major parts", "$200 – $600", 16],
  ["Non-running but complete", "", "$500 – $1,800", 28],
  ["Non-running truck, SUV or diesel", "", "$900 – $3,500", 42],
  ["High-kilometre runner, 10+ years", "", "$900 – $4,000", 50],
  ["Hail damage or insurance write-off", "Mechanically sound", "$1,500 – $8,000", 68],
  ["Newer running car, SUV or truck", "", "$4,000 – $20,000", 100],
] as const;

const situations = [
  [Truck, "It won't start and I can't move it", "Neither can most of what we collect. We bring a winch, a flat deck, and skates for anything on flat tires or no wheels at all. You don't boost it, roll it, or find the key."],
  [MapPin, "It's in a parkade or condo stall", "Beltline and Mission parkades have clearance limits, inner-city alleys in Hillhurst and Inglewood are tight, and some condo boards want notice before a flat deck shows up. Tell us the level and the clearance and we'll plan around it."],
  [FileCheck2, "It's registered to someone who died", "Estate vehicles come up constantly. You'll need documentation showing you have authority to deal with the estate, and what's required depends on its size and structure. Call and describe it before you spend time on it."],
  [CircleDollarSign, "There's still a loan on it", "Lien payouts are routine, particularly on newer write-offs. The lien clears as part of the sale — just mention it upfront so it's arranged rather than discovered on the day."],
  [TriangleAlert, "Insurance wrote it off and I kept it", "That's a buyback, and it's one of our most common Calgary calls because of hail. Salvage and non-repairable status both sell fine. Neither reduces a vehicle to nothing; they remove the option of it going back on the road, and the parts and material value stays intact."],
  [Clock3, "It's at a body shop racking up storage", "Give us the address and whoever's authorisation is needed to release it. Storage accrues daily and it's usually your bill, so this is the one where moving fast genuinely saves you money."],
] as const;

const services = [
  [Car, "Junk Car Removal Calgary", <>A vehicle that won&apos;t start and isn&apos;t worth fixing costs you money every month it sits. Our <Link href="/junk-car-removal-calgary">junk car removal in Calgary</Link> hauls it away free and pays you for it.</>],
  [Recycle, "Scrap Car Removal Calgary", <>When a car has reached the end of the road, <Link href="/scrap-car-removal-calgary">scrap car removal</Link> covers the logistics — getting it out of wherever it&apos;s stuck, off your property, and into proper end-of-life vehicle processing.</>],
  [BadgeDollarSign, "Cash for Scrap Cars", <>If you want the money explained rather than just the pickup, our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> breaks down how curb weight, non-ferrous content and the converter actually add up to your number.</>],
  [Truck, "Free Towing", <>There&apos;s no charge to collect your vehicle, anywhere we serve. <Link href="/free-towing-calgary">Free towing</Link> sits inside every offer we make — the number we quote is the number you&apos;re paid.</>],
] as const;

const supportLinks = [["About Us","/about"],["How It Works","/how-it-works"],["What We Buy","/what-we-buy"],["FAQ","/faq"]] as const;
const homeLocationLinks = [["Airdrie","/cash-for-cars-airdrie"],["Chestermere","/cash-for-cars-chestermere"],["Cochrane","/cash-for-cars-cochrane"],["Okotoks","/cash-for-cars-okotoks"],["Bragg Creek","/cash-for-cars-bragg-creek"],["Strathmore","/cash-for-cars-strathmore"],["High River","/cash-for-cars-high-river"],["Irricana","/cash-for-cars-irricana"],["Diamond Valley","/cash-for-cars-diamond-valley"],["Didsbury","/cash-for-cars-didsbury"],["Nanton","/cash-for-cars-nanton"],["Canmore","/cash-for-cars-canmore"],["Banff","/cash-for-cars-banff"],["Olds","/cash-for-cars-olds"],["Red Deer","/cash-for-cars-red-deer"],["Ponoka","/cash-for-cars-ponoka"],["Brooks","/cash-for-cars-brooks"],["Lethbridge","/cash-for-cars-lethbridge"],["Medicine Hat","/cash-for-cars-medicine-hat"]] as const;

const cityFactors = [
  [Sparkles, "Hail alley runs straight through us", "Calgary sits in the most hail-prone corridor in the country. The storms that roll through in June and July leave behind dented hoods, shattered glass and roofs full of dimples, and insurers write off thousands of mechanically healthy vehicles as a result. Those write-offs are among the best cars we buy, because we're pricing what's underneath rather than the paint."],
  [Snowflake, "Chinooks and road salt do the rest", "A Chinook can swing this city thirty degrees in a day, thawing and refreezing a vehicle repeatedly in the same week. Add five months of brine on Deerfoot, Glenmore and Stoney Trail and corrosion runs ahead of what most of Canada sees. Rust in the rockers, brake lines and frame is the single most common reason a Calgary vehicle becomes unsellable privately."],
  [Zap, "Minus thirty finishes what's already tired", "A cold snap is a stress test. Batteries die, blocks crack, and engines already on borrowed time simply don't come back. The most common call we take all winter is a car that hasn't started since November and isn't worth the repair bill."],
  [MapPin, "And there's nowhere to put it", "In a condo, a Beltline apartment, or anywhere with one assigned stall, a dead vehicle isn't a slow problem — it's an immediate one. Add the City's community standards rules on derelict vehicles stored in view, and a single neighbour complaint is usually all it takes to force the issue."],
] as const;

const process = [
  ["01", "Tell us about the vehicle.", "Year, make, model, whether it runs, roughly what's wrong, and where it's parked. Two minutes on the phone or through the form."],
  ["02", "Get a real number the same day.", "Usually within a couple of hours, in writing, with free towing already inside it. No “up to”, no “starting from”, no fee appearing later."],
  ["03", "Pick a pickup time.", "You get a window rather than a vague day. Same-day collection is normal for morning calls."],
  ["04", "Get paid when we collect.", "We confirm the vehicle matches what you described, complete the bill of sale with you, pay by cash or e-transfer, and load it. About twenty minutes, most of it paperwork."],
] as const;

const areas = [
  ["Northwest", "Tuscany · Bowness · Montgomery · Brentwood · Varsity · Silver Springs · Arbour Lake · Royal Oak · Rocky Ridge · Country Hills · Evanston · Sage Hill · Nolan Hill · Kincora · Hidden Valley · Ranchlands · Dalhousie · Edgemont · Citadel · Kensington · Hillhurst"],
  ["Northeast", "Bridgeland · Renfrew · Marlborough · Rundle · Pineridge · Temple · Whitehorn · Saddle Ridge · Martindale · Falconridge · Castleridge · Taradale · Coral Springs · Skyview Ranch · Cornerstone · Redstone · Monterey Park"],
  ["Southwest", "Beltline · Mission · Marda Loop · Altadore · Killarney · Glamorgan · Signal Hill · Aspen Woods · Springbank Hill · Discovery Ridge · West Springs · Woodbine · Evergreen · Bridlewood · Oakridge · Braeside · Lakeview"],
  ["Southeast", "Forest Lawn · Dover · Ogden · Riverbend · Douglasdale · McKenzie Towne · New Brighton · Copperfield · Mahogany · Auburn Bay · Cranston · Seton · Legacy · Walden · Chaparral · Acadia · Willow Park · Inglewood"],
  ["Industrial and commercial", "Foothills Industrial Park · Manchester · Highfield · Ogden Industrial · Shepard · Great Plains · Franklin · Starfield · Eastfield · Balzac · Rocky View County"],
] as const;

const faqItems = [
  ["How much can I get for a junk car in Calgary?", "Between $200 and $20,000, depending on the vehicle. Curb weight, salvageable parts, the catalytic converter and current scrap metal prices decide where yours lands. The quote is free."],
  ["Do you buy cars that don't run?", "Non-runners are most of what we buy. Dead engines, blown transmissions, cars that haven't started since last winter. We bring the equipment, so you don't need to move or start it."],
  ["Is the towing actually free?", "Yes, everywhere we serve, with nothing deducted at pickup. The number quoted on the phone is the number handed to you."],
  ["How fast can you collect it?", "Offers usually go out within a couple of hours. Pickup is often the same day, next day at the latest. Tell us if you're against a deadline and we'll work to it."],
  ["Do you buy hail-damaged and written-off vehicles?", "Constantly — this is Calgary. Hail damage, collision, insurance write-offs, and both salvage and non-repairable status vehicles are all bought regularly."],
  ["What paperwork do I need?", "Photo ID matching the registered owner and proof of ownership. We complete the bill of sale on site."],
  ["Can you collect from a parkade or condo stall?", "Yes. Tell us the level, any clearance limit, and whether the building needs notice."],
  ["How do you pay?", "Cash on the spot or e-transfer, your choice, sent before the vehicle moves."],
] as const;

function Photo({ src, alt, className = "", position = "center", priority = false }: { src: StaticImageData; alt: string; className?: string; position?: string; priority?: boolean }) {
  return <div className={`photo ${className}`}><Image src={src} alt={alt} fill priority={priority} sizes="(max-width: 820px) 100vw, 50vw" style={{ objectFit: "cover", objectPosition: position }} /></div>;
}

function SectionHeading({ eyebrow, title, intro, light = false }: { eyebrow: string; title: string; intro?: string; light?: boolean }) {
  return <header className={`section-heading${light ? " light" : ""}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{intro ? <p>{intro}</p> : null}</header>;
}

export default function Home() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  const howToSchema = { "@context": "https://schema.org", "@type": "HowTo", name: "How to sell a junk car in Calgary", step: process.map(([, name, text], index) => ({ "@type": "HowToStep", position: index + 1, name, text })) };

  return <>
    <a className="skip-link" href="#main">Skip to main content</a>
    <div className="utility"><div className="shell utility-inner"><span><MapPin aria-hidden="true" /> Calgary &amp; communities across Alberta</span><span className="utility-promise">Same-day pickup · Free towing · Paid at collection</span><a href={phoneHref}><Phone aria-hidden="true" /> {phoneDisplay}</a></div></div>
    <header className="site-header"><div className="shell header-inner">
      <Link className="brand" href="/" aria-label="Junk A Car home"><Image src={logo} alt="Junk A Car" priority sizes="(max-width: 600px) 145px, 180px" /></Link>
      <nav className="desktop-nav" aria-label="Main navigation"><Link href="/">Home</Link><div className="nav-dropdown"><span tabIndex={0}>About Us <ChevronDown aria-hidden="true" /></span><div>{supportLinks.map(([name,href])=><Link href={href} key={href}>{name}</Link>)}</div></div><div className="nav-dropdown"><span tabIndex={0}>Services <ChevronDown aria-hidden="true" /></span><div>{services.map(([, title], index) => <Link key={title} href={["/junk-car-removal-calgary", "/scrap-car-removal-calgary", "/cash-for-scrap-cars-calgary", "/free-towing-calgary"][index]}>{title}</Link>)}</div></div><div className="nav-dropdown"><span tabIndex={0}>Locations <ChevronDown aria-hidden="true" /></span><div>{homeLocationLinks.map(([name,href])=><Link href={href} key={href}>{name}</Link>)}</div></div><Link href="/contact">Contact</Link></nav>
      <a className="header-offer" href="#quote">Get a Quote</a>
      <details className="mobile-menu"><summary aria-label="Open main menu"><Menu aria-hidden="true" /></summary><nav aria-label="Mobile navigation"><Link href="/">Home</Link><details><summary>About Us <ChevronDown aria-hidden="true" /></summary><div>{supportLinks.map(([name,href])=><Link href={href} key={href}>{name}</Link>)}</div></details><details><summary>Services <ChevronDown aria-hidden="true" /></summary><div>{services.map(([, title], index) => <Link key={title} href={["/junk-car-removal-calgary", "/scrap-car-removal-calgary", "/cash-for-scrap-cars-calgary", "/free-towing-calgary"][index]}>{title}</Link>)}</div></details><details><summary>Locations <ChevronDown aria-hidden="true" /></summary><div>{homeLocationLinks.map(([name,href])=><Link href={href} key={href}>{name}</Link>)}</div></details><Link href="/contact">Contact</Link><a className="mobile-offer" href="#quote">Get a Quote</a></nav></details>
    </div></header>

    <main id="main">
      <section className="hero"><div className="hero-orbit one" /><div className="hero-orbit two" /><div className="shell hero-grid">
        <div className="hero-copy"><div className="location-pill"><MapPin aria-hidden="true" /> Calgary, Alberta</div><h1>Cash for Junk Cars in Calgary <span>— Paid on Pickup, Running or Not</span></h1><p>If it won&apos;t start, isn&apos;t worth fixing, or has been sitting since the last cold snap, we&apos;ll buy it. Same-day offer, free towing anywhere in the city, and cash or e-transfer in your hand before it goes on the deck.</p><div className="hero-actions"><a className="button button-primary" href="#quote">Get My Cash Offer <ArrowDownRight aria-hidden="true" /></a><a className="button button-outline" href={phoneHref}><Phone aria-hidden="true" /> Call {phoneDisplay}</a></div><div className="hero-proof"><div><strong>$200–$20K</strong><span>paid for vehicles</span></div><div><strong>Free</strong><span>citywide towing</span></div><div><strong>Today</strong><span>offers &amp; pickup</span></div></div></div>
        <div className="hero-visual"><Photo src={heroPhoto} alt="White SUV lifted for junk car collection in Calgary" className="hero-photo" position="54% center" priority /><div className="floating-badge"><ShieldCheck aria-hidden="true" /><span><strong>AMVIC Licensed</strong>No fees. No deductions.</span></div></div>
        <div id="quote" className="hero-form"><QuoteForm /></div>
      </div><div className="trust-ribbon"><div className="trust-track">{["Same-Day Pickup", "Free Towing", "Paid at Collection", "$200 – $20,000", "AMVIC Licensed"].map((item) => <span key={item}><Check aria-hidden="true" />{item}</span>)}</div></div></section>

      <section className="opening section-space"><div className="shell split-grid"><div className="media-frame"><Photo src={signingPhoto} alt="Owner signing paperwork beside a white Hyundai in Calgary" className="tall-photo" position="55% center" /><div className="photo-note"><HandCoins aria-hidden="true" /><span>One number.<br />One pickup.<br /><strong>One payment.</strong></span></div></div><article><span className="eyebrow">A simpler way to sell</span><h2>The Car You&apos;ve Been Meaning to Deal With</h2><p>There&apos;s one on nearly every street in this city. A minivan that stopped being worth fixing when the transmission went. An F-150 with 340,000 km that finally quit on Deerfoot. Somebody&apos;s first car, parked behind the garage with every intention of getting to it in the spring.</p><p>That&apos;s a junk car, and it doesn&apos;t have to be a rusted shell to qualify. It just has to be a vehicle you&apos;re not driving and aren&apos;t realistically going to drive again.</p><p>We buy them — every make, every model, every condition. You get one number, free towing, and payment when we collect. No classified ad, no lowball offers from tire-kickers, no stranger asking to test drive something that doesn&apos;t start.</p><p>It doesn&apos;t matter where it&apos;s sitting either. A hail-wrecked SUV in Marlborough, a truck with a seized engine behind a shop in Foothills Industrial Park, a sedan in a Beltline parkade stall you&apos;re paying for every month, or a beater on an acreage past Tuscany. If it has a VIN and you own it, we want to make you an offer.</p></article></div></section>

      <section className="value section-space"><div className="shell"><SectionHeading eyebrow="Real numbers, not guesswork" title="How Much Is a Junk Car Worth in Calgary?" intro="This is what everyone arrives wanting to know, so here it is before anything else. Cash for junk car Calgary offers run between $200 and $20,000, and four things decide where yours lands." /><div className="value-grid"><div className="payout-panel"><div className="payout-head"><span>Typical payout ranges</span><strong>$200 <i>to</i> $20,000</strong></div>{payoutRanges.map(([condition, detail, amount, level]) => <div className="payout-row" key={condition}><div><strong>{condition}</strong>{detail ? <span>{detail}</span> : null}</div><div className="meter"><i style={{ width: `${level}%` }} /></div><b>{amount}</b></div>)}</div><div className="factor-panel"><span className="eyebrow">What decides your number</span><div><h3>Curb weight.</h3><p>Steel trades by the tonne, so weight sets the floor before anything else is considered. A compact sedan sits near 1,300 kg; a three-quarter-ton diesel with a steel box can pass 3,000. That difference alone is several hundred dollars.</p></div><div><h3>Salvageable parts.</h3><p>A good engine, a working transmission, clean doors and panels, glass, alloy wheels. On anything newer than roughly fifteen years, this is where most of the value sits — a usable drivetrain is worth far more as a part than as scrap metal.</p></div><div><h3>The catalytic converter.</h3><p>It contains platinum, palladium and rhodium, and on a larger truck it can be worth more than the rest of the vehicle combined. Converter theft is widespread in Calgary, so if yours has been cut off, tell us on the phone. It changes the number, and we&apos;d rather adjust the quote than adjust the payment in your driveway.</p></div><div><h3>Current scrap metal prices.</h3><p>Ferrous and non-ferrous markets move week to week. We quote on today&apos;s numbers, not last year&apos;s.</p></div></div></div><div className="section-footer"><p>A 2009 Corolla with a blown engine in Forest Lawn and a 2021 Silverado with hail dents in Mahogany are completely different conversations. The only way to know yours is to ask, and the quote costs nothing.</p><div><a className="button button-primary" href="#quote">Get My Free Quote</a><a className="text-link" href={phoneHref}>Call {phoneDisplay} <ArrowRight aria-hidden="true" /></a></div></div></div></section>

      <section className="situations section-space"><div className="shell"><SectionHeading eyebrow="No situation too complicated" title="Whatever's Stopping You, We've Dealt With It" intro="Most people don't hesitate because they're unsure what the car is worth. They hesitate because something about their situation feels complicated. These come up every week." /><div className="situation-grid">{situations.map(([Icon, title, text]) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div><p className="section-note">Not on the list? Call and describe it. Two minutes on the phone beats a week of wondering.</p></div></section>

      <section id="what-we-buy" className="what-we-buy section-space"><div className="shell"><SectionHeading eyebrow="Running or not" title="We Buy Junk Cars in Almost Any Condition" /><div className="buy-grid"><div><Photo src={trailerPhoto} alt="Damaged black Ford Fiesta secured on a trailer for pickup" className="wide-photo" /><div className="buy-tag"><CircleDollarSign aria-hidden="true" /><span>Too far gone?<br /><strong>It still has value.</strong></span></div></div><article><h3>Vehicle types</h3><ul className="check-list"><li>Sedans, hatchbacks and coupes</li><li>SUVs and crossovers</li><li>Half-tons, three-quarter-tons and one-tons</li><li>Duallies and diesel pickups</li><li>Minivans and cargo vans</li><li>Box trucks</li><li>Commercial, work and fleet vehicles</li></ul><h3>Conditions we accept</h3><ul className="check-list"><li>Won&apos;t start or has a dead battery</li><li>Seized engine</li><li>Blown head gasket or cracked block</li><li>Failed transmission or differential</li><li>Hail or collision damage</li><li>Insurance write-off, salvage or non-repairable status</li><li>Fire or flood damage</li><li>Rusted rockers, brake lines or frames</li><li>Failed out-of-province inspection</li><li>High kilometres</li><li>Already stripped for parts</li><li>Abandoned, inherited or estate vehicle</li></ul><p className="accent-copy">If you&apos;re looking at it wondering whether it&apos;s too far gone to be worth anything, it almost certainly isn&apos;t.</p></article></div></div></section>

      <section id="services" className="services section-space"><div className="shell"><SectionHeading light eyebrow="One call handles it" title="Junk and Scrap Services Across Calgary" /><div className="service-grid">{services.map(([Icon, title, text]) => <article key={title}><div className="service-icon"><Icon aria-hidden="true" /></div><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

      <section className="city section-space"><div className="shell city-grid"><div className="city-sticky"><span className="eyebrow">Built for where we live</span><h2>This City Is Unusually Hard on Cars</h2><Photo src={suvPhoto} alt="White Ford Escape awaiting junk car collection in Calgary" className="city-photo" /></div><div>{cityFactors.map(([Icon, title, text]) => <article className="city-note" key={title}><Icon aria-hidden="true" /><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

      <section id="how-it-works" className="process section-space"><div className="shell"><SectionHeading eyebrow="From driveway to done" title="Four Steps, Usually Done Inside 24 Hours" /><div className="process-grid">{process.map(([number, title, text], index) => <article key={number}><div className="step-number"><span>{number}</span>{index === 0 ? <Car /> : index === 1 ? <BadgeDollarSign /> : index === 2 ? <Clock3 /> : <HandCoins />}</div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="centered"><a className="button button-primary" href="#quote">Start With a Free Quote <ArrowRight aria-hidden="true" /></a></div></div></section>

      <section id="areas" className="coverage section-space"><div className="shell"><SectionHeading light eyebrow="Citywide and beyond" title="Junk Cars for Cash Across Calgary and Alberta" /><div className="coverage-grid"><div className="coverage-photo"><Photo src={sedanPhoto} alt="Silver Saturn ready for cash vehicle pickup in Calgary" className="coverage-image" position="center 63%" /><div><MapPin aria-hidden="true" /><strong>Free Calgary pickup</strong><span>Residential, commercial and industrial</span></div></div><div className="area-list">{areas.map(([name, places], index) => <details key={name} open={index === 0}><summary>{name}<ChevronRight aria-hidden="true" /></summary><ul>{places.split(" · ").map((place) => <li key={place}>{place}</li>)}</ul></details>)}</div></div><p className="landmark-note">If you&apos;re near Chinook Centre, Market Mall, Sunridge, Deerfoot City, the Stampede Grounds, McMahon Stadium, the University of Calgary or SAIT — or anywhere along Deerfoot, Stoney, Crowchild, Glenmore, Macleod or 17th Avenue SE — we&apos;ll come to you.</p><div className="beyond"><div><span className="eyebrow">Beyond the city</span><h3>Free collection across Alberta</h3></div><ul>{["Chestermere", "Airdrie", "Cochrane", "Bragg Creek", "Okotoks", "Irricana", "Strathmore", "High River", "Diamond Valley", "Didsbury", "Nanton", "Olds", "Canmore", "Banff", "Red Deer", "Ponoka", "Brooks", "Lethbridge", "Medicine Hat"].map((place) => <li key={place}>{place}</li>)}</ul></div></div></section>

      <section className="details section-space"><div className="shell details-grid"><article><FileCheck2 className="detail-icon" aria-hidden="true" /><span className="eyebrow">Keep it simple</span><h2>What You Need to Sell a Junk Car in Alberta</h2><p>Photo ID matching the registered owner, and proof of ownership — usually the registration. We complete the bill of sale with you at pickup and leave you a copy, so there&apos;s nothing to print or prepare in advance.</p><p>Take your licence plate off before we tow. In Alberta a plate belongs to the registered owner, not the vehicle, and people forget this constantly.</p><p>Afterward, take the plate and your copy of the bill of sale to any Alberta registry agent to cancel or transfer the registration. Then call your insurer — if you&apos;d prepaid a policy on a vehicle you no longer own, there&apos;s often a refund on the unused portion, and nobody phones to tell you about it.</p><Photo src={paperworkPhoto} alt="Silver Mercedes and sale paperwork prepared in a Calgary garage" className="detail-photo" /></article><article className="recycling"><Recycle className="detail-icon" aria-hidden="true" /><span className="eyebrow">A responsible next life</span><h2>What Happens to Your Car After We Take It</h2><p>Fluids come out first — engine oil, coolant, brake and transmission fluid, and whatever fuel is left — before anything else happens. Air conditioning refrigerant is recovered rather than vented. Batteries, tires and mercury switches go to their own streams. Anything with resale life is removed and inventoried, which is how used parts reach repair shops across Calgary. What remains is separated into ferrous and non-ferrous metal and recycled.</p><p>It means your old car ends up back in the supply chain instead of leaking into ground that drains toward the Bow.</p><Photo src={drivewayPhoto} alt="Black Chevrolet ready for vehicle recycling in Calgary" className="detail-photo" /></article></div></section>

      <section id="faq" className="faq section-space"><div className="shell faq-grid"><div><span className="eyebrow">Straight answers</span><h2>Frequently Asked Questions</h2><p>Still wondering about your vehicle? Call and talk to a real person.</p><a className="text-link" href={phoneHref}><Phone aria-hidden="true" />{phoneDisplay}</a></div><div className="faq-list">{faqItems.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<i><ChevronRight aria-hidden="true" /></i></summary><p>{answer}</p></details>)}</div></div></section>

      <section className="final-cta"><div className="cta-orbit" /><div className="shell"><span className="eyebrow">Your driveway could be clear today</span><h2>Turn It Into Cash Today</h2><p>Stop paying insurance, registration and a parking stall for something you&apos;re never driving again. One call, one pickup, and it&apos;s off your property today.</p><div><a className="button button-white" href={phoneHref}><Phone aria-hidden="true" />Call {phoneDisplay}</a><a className="button button-dark" href="#quote">Get My Free Cash Offer <ArrowRight aria-hidden="true" /></a></div></div></section>
    </main>

    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-brand"><Image src={logo} alt="Junk A Car" sizes="190px" /><p>Fair cash offers, free towing, and same-day pickup across Calgary and Alberta.</p><a href={phoneHref}><Phone aria-hidden="true" />{phoneDisplay}</a><a href="mailto:info@junkacar.ca">info@junkacar.ca</a><p>AMVIC licensed company</p></div><div><h3>Services</h3>{services.map(([, title], index) => <Link key={title} href={["/junk-car-removal-calgary", "/scrap-car-removal-calgary", "/cash-for-scrap-cars-calgary", "/free-towing-calgary"][index]}>{title}</Link>)}</div><div className="footer-locations"><h3>Top Locations</h3>{homeLocationLinks.slice(0,8).map(([name,href])=><Link href={href} key={href}>{name}</Link>)}</div><div><h3>Visit or contact</h3><p>6915 40 St NE<br />Calgary, AB T3J 4H2</p><p>Daily: 7:00 am–11:00 pm</p><Link href="/contact">Contact us</Link><a className="footer-quote" href="#quote">Request a quote <ArrowRight aria-hidden="true" /></a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Junk A Car</span><span>AMVIC licensed company · Serving Calgary &amp; Alberta</span></div></footer>
    <div className="mobile-actions"><a href={phoneHref}><Phone aria-hidden="true" />Call now</a><a href="#quote"><BadgeDollarSign aria-hidden="true" />Get offer</a></div>
    <JsonLd data={howToSchema} /><JsonLd data={faqSchema} />
  </>;
}
