export type QuoteLead = { name: string; phone: string; vehicle: string; city: string; email: string; message: string; sourcePage: string; pageUrl: string; ipAddress: string; browser: string };

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
const display = (value: string, fallback = "Not provided") => escapeHtml(value || fallback).replace(/\n/g, "<br>");

export function buildQuoteEmail(lead: QuoteLead, reference: string, submittedAt: Date) {
  const submitted = new Intl.DateTimeFormat("en-CA", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Edmonton" }).format(submittedAt);
  const phoneHref = `tel:${lead.phone.replace(/[^\d+]/g, "")}`;
  let sourceUrl = "https://www.junkacar.ca/";
  try { const candidate = new URL(lead.pageUrl || lead.sourcePage, sourceUrl); if (["http:", "https:"].includes(candidate.protocol)) sourceUrl = candidate.toString(); } catch { /* use canonical */ }
  const text = ["NEW CASH OFFER REQUEST", `Reference: ${reference}`, `Submitted: ${submitted} (Alberta time)`, "", `Name: ${lead.name}`, `Phone: ${lead.phone}`, `Email: ${lead.email || "Not provided"}`, `Vehicle: ${lead.vehicle}`, `City or town: ${lead.city}`, `Notes: ${lead.message || "None"}`, "", `Page URL: ${sourceUrl}`, `IP Address: ${lead.ipAddress}`, `Browser: ${lead.browser}`].join("\n");
  const html = `<!doctype html><html lang="en"><body style="margin:0;background:#eef3f9;font-family:Arial,sans-serif;color:#10213d"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:680px;background:#fff;border-top:5px solid #0759d9"><tr><td style="padding:30px 34px;background:#052b7a;color:#fff"><p style="margin:0 0 8px;color:#8de6b0;font-weight:800;text-transform:uppercase;letter-spacing:2px">New website inquiry</p><h1 style="margin:0">Cash offer request</h1><p style="color:#cbd8ef">${escapeHtml(submitted)} · ${escapeHtml(reference)}</p></td></tr><tr><td style="padding:30px 34px"><p style="color:#178447;font-weight:800;text-transform:uppercase">Vehicle</p><h2>${display(lead.vehicle)}</h2><p>Pickup in <strong>${display(lead.city)}</strong></p><hr style="border:0;border-top:1px solid #dce4ef"><p><strong>Customer:</strong> ${display(lead.name)}</p><p><strong>Phone:</strong> <a href="${escapeHtml(phoneHref)}">${display(lead.phone)}</a></p><p><strong>Email:</strong> ${lead.email ? `<a href="mailto:${escapeHtml(lead.email)}">${display(lead.email)}</a>` : "Not provided"}</p><p><strong>Notes:</strong><br>${display(lead.message, "No additional notes")}</p><p style="font-size:13px;color:#617089">Submitted from <a href="${escapeHtml(sourceUrl)}">${escapeHtml(sourceUrl)}</a><br>IP: ${display(lead.ipAddress)}<br>Browser: ${display(lead.browser)}</p></td></tr></table></td></tr></table></body></html>`;
  return { html, text };
}
