import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/silver-mercedes-open-trunk-calgary.jpeg";
import ranchImage from "@/assets/images/damaged-ford-fiesta-trailer-pickup-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Cochrane | Free Towing, Paid at Pickup", description: "Cash for junk cars in Cochrane, AB. We buy non-running, damaged and scrap vehicles, tow free from hillside driveways and acreages, and pay on pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-cochrane" }, openGraph: { title: "Cash for Junk Cars Cochrane | Free Towing, Paid at Pickup", description: "Cash for junk cars in Cochrane, AB. We buy non-running, damaged and scrap vehicles, tow free from hillside driveways and acreages, and pay on pickup.", url: "https://www.junkacar.ca/cash-for-cars-cochrane", type: "website", images: [{ url: heroImage.src, alt: "Vehicle ready for free cash pickup in Cochrane" }] } };

const data: ServicePageData = {
  path: "/cash-for-cars-cochrane", label: "Cash for Cars Cochrane", h1: "Cash for Junk Cars in Cochrane — Hillside, Acreage or Downtown",
  subhead: "We're about thirty-five minutes up the 1A. Whether the vehicle is parked on a steep Sunset Ridge driveway, behind a barn out toward Grand Valley, or in a stall near Historic Downtown, we'll give you a real number the same day, tow it free, and pay you on the spot.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "Vehicle in a garage ready for cash pickup in Cochrane", trustItems: ["Free Cochrane towing", "Hillside pickups", "Acreages covered", "Paid on the spot"],
  sections: [
    { eyebrow: "Why Cochrane", title: "What Cochrane's Hills Do to Vehicles", intro: ["Cochrane is beautiful because of its terrain, and its terrain is exactly what wears vehicles out here. Four things come up again and again."], cards: [
      { title: "Everything is uphill from somewhere", text: <>Most of the town sits on the slopes above the Bow River valley. Heritage Hills, Sunset Ridge, Fireside, Heartland, Rivercrest, GlenEagles, Precedence — nearly every drive home involves a climb, and every drive out involves a descent. Then there&apos;s the Big Hill on the 1A itself, which every commuter climbs twice a day.<br /><br />That&apos;s hard on brakes, transmissions and cooling systems in a way flat-city driving isn&apos;t. Brake pads, rotors and calipers get replaced more often, automatic transmissions run hotter under load, and radiators and water pumps work harder. In winter, the grades are exactly where tired vehicles finally give up.</> },
      { title: "The 1A and Highway 22 bottleneck", text: "Anyone who commutes into Calgary from Cochrane knows the traffic on Highway 1A and around the Highway 22 interchange. Stop-and-go through town, highway speed to Crowchild or Stoney Trail, then stop-and-go again at the city edge. That pattern is tough on clutches, brakes and engines, and it's why plenty of seven- or eight-year-old Cochrane vehicles feel older than they are." },
      { title: "Ranch country at the edge of town", text: "Past the subdivisions, Cochrane is still ranch and acreage land — Grand Valley, Horse Creek, Weedon, the Glenbow area and out toward Bottrel and Water Valley. Ranch trucks here haul feed, pull stock trailers and run gravel roads every day. They stay in service a long time and tend to accumulate on properties once they're retired, often two or three to a yard." },
      { title: "Chinooks straight off the mountains", text: "Cochrane sits closer to the Rockies than Calgary does, and the Chinook swings are sharper. Rapid thaw-and-refreeze cycles push water into seams, cab corners and rocker panels, and rust moves faster as a result — particularly on brake lines, wheel wells and the underside of older trucks." },
    ]},
    { eyebrow: "Valuation", title: "What Cochrane Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Older car, non-running, complete", "$250 – $800"], ["SUV or crossover with a failed transmission", "$500 – $1,800"], ["Ranch half-ton, non-running", "$700 – $2,000"], ["3/4-ton, one-ton or diesel, complete", "$1,000 – $3,500"], ["Hail-damaged, mechanically sound", "$1,500 – $8,000"], ["Newer running vehicle", "$4,000 – $20,000"]] }, after: ["Curb weight sets the floor. Salvageable parts — particularly drivetrain components on trucks and SUVs — push it up. The catalytic converter is valued separately. Rust pulls the number down, and current scrap metal prices move the whole thing.", "A failed transmission from years of hill driving lowers the offer far less than people expect. The rest of the vehicle still carries weight, panels, glass and parts value — which is why a vehicle a shop has written off as “not worth fixing” still gets a real number from us."] },
    { eyebrow: "One call handles it", title: "Our Services in Cochrane", intro: ["Hillside driveway, ranch yard or downtown stall — each of these services is set up for Cochrane's terrain, and every one comes with free towing and payment on collection."], cards: [
      { title: "Junk Car Removal in Cochrane", text: <>A non-running vehicle on a Heritage Hills or Sunset Ridge slope can&apos;t just be pushed onto a trailer. Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> uses a controlled winch pull set up for the grade, so the vehicle comes off safely without anyone trying to roll a car with seized brakes down a steep driveway.</> },
      { title: "Scrap Car Removal in Cochrane", text: <>Ranch trucks that have finished their working lives out toward Grand Valley and Weedon usually end up as scrap. Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> collects them from pasture, yard or shelterbelt and puts them through proper end-of-life processing, with oils and coolant captured rather than left on land that drains toward the Bow.</> },
      { title: "Cash for Scrap Cars in Cochrane", text: <>A truck with a transmission cooked by the Big Hill still carries its engine, axles, panels and converter. Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> shows how those parts, plus curb weight and current metal prices, turn a “not worth fixing” vehicle into a real offer.</> },
      { title: "Free Towing in Cochrane", text: <>The run up the 1A costs you nothing, and neither does a long gravel approach off Horse Creek Road. <Link href="/free-towing-calgary">Free towing</Link> is built into every Cochrane offer — town, acreage or ranch — with no charge for slope work and nothing deducted on arrival.</> },
    ]},
    { eyebrow: "Local situations", title: "Getting a Dead Vehicle Off a Cochrane Property", cards: [
      { title: "“The driveway is steep and it won't start.”", text: "This is the Cochrane question. A non-running vehicle on a steep slope needs a controlled winch pull rather than a push, and sometimes the truck has to set up at an angle at the bottom. It's entirely normal work for us. Tell us whether the vehicle faces uphill or downhill, and send a photo if you can." },
      { title: "“It's frozen to the driveway.”", text: "Happens every winter on shaded, north-facing slopes. Usually manageable. If it's genuinely frozen in, we may suggest waiting for a warmer day rather than damaging your driveway or the vehicle getting it free." },
      { title: "“It's at the back of the acreage.”", text: "Long gravel approaches, pasture access, vehicles tucked behind a barn or a shelterbelt — all routine. Soft spring ground is the only real limit, and we'll be honest if we need to wait." },
      { title: "“There are several on the property.”", text: "One visit, one quote for the lot, and a better per-vehicle number than selling them one at a time." },
      { title: "“It's in a Downtown or Riverfront stall.”", text: "Tell us the building and any access or clearance rules. Some complexes need notice before a flat deck arrives." },
    ]},
    { eyebrow: "Winter timing", title: "The Best Time to Sell a Junk Car in Cochrane", image: ranchImage, imageAlt: "Non-running vehicle prepared for pickup near Cochrane before winter", intro: ["Honestly, the answer is before the next winter rather than after it. A non-running vehicle that sits through a Cochrane winter goes backwards quickly: batteries freeze and split, fuel degrades, brakes seize to the rotors, and mice move into the air box and wiring. Every one of those lowers what's salvageable.", "There's also a practical reason. Steep driveways are much easier to work on when they're dry than when they're sheet ice. Late summer and fall pickups on sloped properties are faster, safer and easier on your driveway. If the vehicle's future is already decided, getting it gone before the first hard freeze usually means a better number and a simpler pickup."] },
    { eyebrow: "Coverage", title: "Where We Collect in Cochrane", cards: [
      { title: "In town", text: "Heritage Hills, Sunset Ridge, Fireside, Heartland, Riversong, Rivercrest, GlenEagles, Glenbow, Bow Meadows, Precedence, Jumping Pound Ridge, West Terrace, West Valley, East End, Historic Downtown, and the Quarry and Riverfront area." },
      { title: "Around Cochrane", text: "Acreages and ranches in Rocky View County along Highway 22, Highway 1A, Highway 567 and Horse Creek Road, including Grand Valley, Weedon, Bottrel and toward Water Valley, plus the Springbank acreages to the south." },
    ]},
    { eyebrow: "Four simple steps", title: "How It Works", cards: [{ title: "Describe it.", text: "Year, make, model, condition — and whether it's on a slope or at the back of a property." }, { title: "Get a number the same day.", text: "Free towing already inside it." }, { title: "Pick a window.", text: "Same day or next for Cochrane." }, { title: "Get paid.", text: "Bill of sale, cash or e-transfer, and we load it. About twenty minutes." }] },
    { eyebrow: "Paperwork", title: "What to Have Ready", intro: ["Photo ID matching the registered owner and proof of ownership. We complete the bill of sale at pickup and leave you a copy.", "Take your licence plate off — in Alberta it stays with you. Then cancel or transfer the registration at a registry agent in Cochrane or anywhere in Alberta, and ask your insurer about a refund on unused prepaid coverage.", "Ranch trucks registered to a farm corporation or family partnership are common around Cochrane. They're workable with the right signing authority — mention it when you call."] },
    { eyebrow: "Nearby", title: "Communities Near Cochrane", intro: ["Free towing also covers Bragg Creek, Canmore and Airdrie, plus Calgary's northwest and the Rocky View land in between."] },
  ],
  faqs: [["Can you get a non-running car off a steep driveway?", "Yes. We use a controlled winch pull and set up to suit the slope. A photo helps us plan."], ["Do you charge extra for acreage pickups?", "No. Rocky View acreages and ranches are covered at no extra cost, including long gravel approaches."], ["How long does it take you to get to Cochrane?", "Around thirty-five minutes, depending on 1A traffic. Same-day pickup is common for morning calls."], ["The transmission is gone. Is it worth anything?", "Yes. A failed transmission lowers the offer less than you'd think — the rest of the vehicle still carries value."], ["It's registered to our ranch company.", "Workable with signing authority. Call first so the paperwork is ready on the day."], ["How do you pay?", "Cash on the spot or e-transfer, before the vehicle moves."]],
  finalTitle: "Get a Cochrane Pickup Booked", finalText: "Tell us where it's parked and how steep it is. We'll take it from there — and you'll have a number within a couple of hours.", finalCta: "Get a Free Offer",
};
export default function CashForCarsCochranePage() { return <ServicePage data={data} />; }
