import type{Metadata}from"next";import{ServicePage,type ServicePageData}from"@/components/service-page";import hero from"@/assets/images/silver-mercedes-open-trunk-calgary.jpeg";
export const metadata:Metadata={title:"How It Works | Selling Your Junk Car for Cash in Calgary",description:"Exactly what happens when you sell a vehicle to us in Calgary — from the first call to payment — including timings, paperwork and what can go wrong.",alternates:{canonical:"https://www.junkacar.ca/how-it-works"}};
const data:ServicePageData={path:"/how-it-works",label:"How It Works",h1:"How Selling Your Vehicle to Us Actually Works",subhead:"Most people have never sold a car this way. Here is the full process from first contact to payment, including timings and the details that catch people out.",primaryCta:"Start With a Free Offer",heroImage:hero,heroAlt:"Vehicle prepared for a simple cash sale in Calgary",trustItems:["Two-minute first step","Tow included","Clear pickup window","Paid before loading"],sections:[
{eyebrow:"Step one",title:"Step One — You Tell Us About the Vehicle",cards:[{title:"What we need",text:"Year, make, model, whether it runs, roughly what's wrong, where it sits, your name and phone number. Photos help with unusual vehicles or tight access."},{title:"Why honesty pays",text:"Mention missing converters, engines or transmissions, severe condition and missing paperwork. None automatically stops the sale, but each affects an accurate quote."},{title:"How long it takes",text:"Two or three minutes by phone or form."}]},
{eyebrow:"Step two",title:"Step Two — We Come Back With a Number",cards:[{title:"What the offer includes",text:"One final figure with towing, fuel, distance and disposal already included."},{title:"Timing",text:"Usually within a couple of hours the same day; unusual vehicles may need until the next morning."},{title:"No pressure",text:"Think about it and compare quotes. Ask every buyer whether towing is included and whether the figure is final."}]},
{eyebrow:"Step three",title:"Step Three — We Book a Time",intro:["Morning Calgary calls commonly qualify for same-day pickup; afternoon calls are typically next day. Canmore, Banff, Red Deer, Ponoka, Lethbridge and Medicine Hat run on scheduled routes.","You receive a time window and a call if timing changes. Tell us about moves, possession dates, landlord notices or flights."],lists:[{title:"Before we arrive",items:["Empty the glovebox, console, seats, pockets, trunk and spare-wheel well.","Remove your licence plate.","Find matching photo ID and ownership documents.","Clear an easy path if practical; you do not need to wash, start or move the vehicle."]}]},
{eyebrow:"Step four",title:"Step Four — Pickup Day",intro:["We confirm the vehicle matches its description, complete the bill of sale, pay by cash or e-transfer before it moves, then load it with a flat deck, winch and skates as needed.","The appointment takes about twenty minutes, mostly paperwork."]},
{eyebrow:"After the sale",title:"After the Sale — Two Things People Forget",cards:[{title:"Cancel or transfer registration",text:"Take your plate and bill of sale to any Alberta registry agent."},{title:"Call your insurer",text:"Cancel coverage and ask about a refund for any unused prepaid term."}]},
{eyebrow:"Call first",title:"Situations That Need a Conversation First",cards:[{title:"The vehicle isn't in your name",text:"Estate, property, tenant and never-transferred vehicles need supporting documents."},{title:"There's still finance",text:"Lien payouts are routine but must be arranged."},{title:"It is at a shop or impound",text:"We need the address and release authorisation; storage often accrues daily."},{title:"You won't be there",text:"An authorised person can sign while payment goes to you by e-transfer."},{title:"Access is difficult",text:"Tight garages, parkades, soft ground, alleys and slopes are manageable when described in advance."}]}],faqs:[],finalTitle:"Start Whenever You're Ready",finalText:"Year, make, model and what's wrong with it. That's the whole first step.",finalCta:"Get a Free Offer"};export default function Page(){return <ServicePage data={data}/>}
