import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/white-ford-escape-junk-car-calgary.jpeg";
import truckImage from "@/assets/images/lifted-white-suv-junk-car-calgary.jpeg";

export const metadata: Metadata = {
  title: "Cash for Junk Cars Chestermere | Free Towing, Paid Same Day",
  description: "Cash for junk cars in Chestermere, AB. We buy non-running, damaged and scrap vehicles, tow free from any driveway or lake property, and pay on pickup.",
  alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-chestermere" },
  openGraph: { title: "Cash for Junk Cars Chestermere | Free Towing, Paid Same Day", description: "Cash for junk cars in Chestermere, AB. We buy non-running, damaged and scrap vehicles, tow free from any driveway or lake property, and pay on pickup.", url: "https://www.junkacar.ca/cash-for-cars-chestermere", type: "website", images: [{ url: heroImage.src, alt: "Vehicle ready for free cash pickup in Chestermere" }] },
};

const data: ServicePageData = {
  path: "/cash-for-cars-chestermere", label: "Cash for Cars Chestermere",
  h1: "Cash for Junk Cars in Chestermere — Free Pickup, Paid the Same Day",
  subhead: "We're about twenty minutes east along 17th Avenue. One vehicle or three, running or long dead, we'll make you a real offer the same day, tow everything away free, and pay you before it leaves the driveway.",
  primaryCta: "Get My Cash Offer", heroImage, heroAlt: "White Ford Escape ready for cash car pickup in Chestermere",
  trustItems: ["Same-day offers", "Free Chestermere towing", "Multi-vehicle pickup", "Paid on the spot"],
  sections: [
    { eyebrow: "Why Chestermere", title: "Big Households, Busy Driveways", intro: ["Chestermere looks different from most of the Calgary region, and the way vehicles accumulate here is different too. Three patterns account for almost every call we take from the lake."], cards: [
      { title: "Three and four vehicles per address is normal", text: <>Homes in Kinniburgh, Westmere, Rainbow Falls, Chelsea and Dawson&apos;s Landing tend to be larger, and so are the households living in them — adult children still at home, extended family under one roof, several people working different shifts in different places. That means more vehicles per address than almost anywhere else we serve.<br /><br />More vehicles means more of them eventually become the one nobody drives. It stays because it might be useful someday, it keeps getting insured because cancelling feels like a decision nobody wants to make, and it quietly occupies driveway space a working vehicle should have. Multiply that across a few years and it&apos;s not unusual to find two retired vehicles at one address.</> },
      { title: "The southeast industrial commute", text: <>A large share of Chestermere works in Calgary&apos;s southeast — Foothills Industrial, Shepard, Great Plains, and the distribution centres along 84th Street and Stoney Trail. That&apos;s a short commute on paper, but it&apos;s hard on vehicles: stop-start traffic on 17th Avenue and Highway 1, gravel and debris tracked out of industrial yards, and heavy salt all winter.<br /><br />Work vehicles here age fast and quietly. Brake lines, rockers, exhaust hangers and suspension components give out before the odometer says they should, and the repair bills arrive in clusters.</> },
      { title: "Lake trucks and tow rigs", text: <>Chestermere Lake shapes summer here. Boats, pontoons, sea-doo trailers and camping trailers mean plenty of half-tons and SUVs spend part of every year towing. Launch ramps, steep hitch angles and short heavy-load trips wear transmissions, rear ends and brakes in ways that never show up on the odometer.<br /><br />A tired tow rig frightens private buyers, who ask the right questions about the transmission. It frightens us much less, because we&apos;re pricing weight and parts rather than how many more summers of towing it has left.</> },
    ]},
    { eyebrow: "Valuation", title: "What Chestermere Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Older sedan or compact, non-running", "$250 – $800"], ["SUV or minivan, non-running but complete", "$500 – $1,800"], ["Tow-rig half-ton with a tired drivetrain", "$700 – $2,200"], ["Non-running 3/4-ton or diesel", "$900 – $3,500"], ["Hail-damaged, mechanically sound", "$1,500 – $8,000"], ["Two or more vehicles, one address", "Per-vehicle offer improves"]] }, after: ["Curb weight sets the floor, and trucks carry a lot of it. Salvageable parts push the number up — truck drivetrain components in particular move steadily across Alberta. The catalytic converter is valued separately and, on a larger truck, can be worth more than the rest of the vehicle. Current scrap metal prices move the whole thing week to week.", "Clearing more than one vehicle at the same address is efficient for us, and the per-vehicle offer improves as a result. If you've got two or three sitting around, it's worth quoting them together rather than one at a time."] },
    { eyebrow: "One call handles it", title: "Our Services in Chestermere", intro: ["Most Chestermere calls involve more than one vehicle, so every service below can be booked for a single car or a whole driveway — with free towing and payment on the day either way."], cards: [
      { title: "Junk Car Removal in Chestermere", text: <>The retired second or third vehicle is our most common Chestermere job — sitting on a side yard in Rainbow Falls or taking up half a double driveway in Kinniburgh. Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> gets it out of tight side yards with skates and a winch, and clears several at one address in a single visit.</> },
      { title: "Scrap Car Removal in Chestermere", text: <>Work trucks that have given years to the southeast industrial parks often end up as scrap once the frame, brake lines and exhaust all go at once. Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> collects them and puts them through proper end-of-life processing, with fluids captured rather than left to seep near the lake or the irrigation canals.</> },
      { title: "Cash for Scrap Cars in Chestermere", text: <>A tow rig that&apos;s pulled a boat every summer is heavy, full of truck parts, and usually still has its catalytic converter — all of which count. Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> breaks down how weight, drivetrain components and the converter add up, so you can see why a worn-out lake truck is still worth real money.</> },
      { title: "Free Towing in Chestermere", text: <>One vehicle or three, lakefront lot or acreage off Highway 791 — collection costs nothing. <Link href="/free-towing-calgary">Free towing</Link> is built into every offer, and there&apos;s no extra charge per vehicle when we clear more than one from the same address.</> },
    ]},
    { eyebrow: "Local situations", title: "Situations We Sort Out in Chestermere", cards: [
      { title: "“It's registered to a family member who isn't here.”", text: "Common in larger households — the car is in a parent's or sibling's name, and they're away, working out of town, or overseas. The registered owner needs to sign the bill of sale, or to have authorised someone in advance with proper documentation. Call before booking and we'll tell you exactly what paperwork makes it work." },
      { title: "“We have three and want to clear two.”", text: "Describe both and we'll quote the pair. One visit, one payment, and a better number per vehicle than you'd get selling them separately." },
      { title: "“It's parked beside the house on the side yard.”", text: "Side yards on newer Chestermere lots can be narrow, with fences, gas meters and utility boxes in the way. Tell us the gap width and what's blocking it, and we'll bring the right equipment — skates and a winch get most vehicles out of spaces people assume are impossible." },
      { title: "“It was a work truck and it's done.”", text: "Retired work trucks from the southeast industrial parks are routine for us. If the truck is registered to a company, we'll need someone with signing authority — mention it upfront so it's ready on the day." },
      { title: "“It sat all winter and the battery's dead.”", text: "Completely normal. We don't need it to start, and we don't need the keys to be found. We winch it onto the deck." },
    ]},
    { eyebrow: "The hidden bill", title: "What That Extra Vehicle Is Actually Costing You", image: truckImage, imageAlt: "Heavy SUV occupying driveway space near Chestermere", intro: ["Most Chestermere households underestimate this, because the costs are spread out and nobody adds them up.", "There's the insurance — even a basic policy on an unused vehicle runs to hundreds of dollars a year. There's the annual registration. There's the lost driveway space, which in winter often means a working vehicle ends up on the street. And there's depreciation: a parked car loses value faster than a driven one, because batteries freeze, brakes seize, seals dry out and mice move in.", "Add those together over two or three years and the “spare” has often cost more than it's now worth. Selling it stops the bleeding immediately, and on many policies the unused prepaid portion comes back to you as a refund."] },
    { eyebrow: "Coverage", title: "Where We Collect in Chestermere", cards: [
      { title: "Around the lake and throughout the city", text: "Kinniburgh, Westmere, Rainbow Falls, Lakepointe, The Cove, Chelsea, Dawson's Landing, Clearwater Park, Westcreek, Waterford, Sunset Harbour, East Lake Hills, and the older homes along Chestermere Boulevard and the lakeshore." },
      { title: "Commercial strip and surrounding land", text: "Businesses along Chestermere Boulevard and Rainbow Road, plus acreages and farmland in Rocky View County east and south of town, along Highway 1, Highway 791 and the Western Irrigation District canal roads." },
    ], after: ["Lake-access lots and narrow side yards are workable. Soft ground after rain or spring melt is the only real limit — if we'd rut your yard, we'll say so and come back when it firms up."] },
    { eyebrow: "Four simple steps", title: "From Phone Call to Paid", cards: [
      { title: "Tell us what you have.", text: "Year, make, model and condition for each vehicle." }, { title: "Get one number per vehicle, or one for the lot.", text: "Same day, with free towing built in." }, { title: "Book a window.", text: "Same-day pickup is usually available for morning calls." }, { title: "Sign and get paid.", text: "Bill of sale on site, cash or e-transfer, and each vehicle is loaded. About twenty minutes per vehicle." },
    ]},
    { eyebrow: "Paperwork", title: "What Alberta Requires", intro: ["Photo ID matching the registered owner and proof of ownership. We complete the bill of sale with you and leave you a copy.", "Remove the plate before we load — Alberta plates belong to the owner, not the vehicle. Then visit any registry agent to cancel or transfer the registration, and call your insurer about prepaid coverage.", "If the vehicle is in a family member's name, a company's name, or still carrying a loan, tell us before we book. Each is routine, but each needs a little preparation."] },
    { eyebrow: "Nearby", title: "Communities Near Chestermere", intro: ["Free towing also covers Strathmore, Irricana and Airdrie, plus Calgary's east side and the county land between."] },
  ],
  faqs: [["Can you take more than one vehicle?", "Yes, and it improves the per-vehicle offer. Describe them all when you call and we'll quote the group."], ["The car is in my father's name. Can I sell it?", "He needs to sign, or to have authorised you in advance with the right documentation. Call first and we'll tell you exactly what's needed."], ["How quickly can you get to Chestermere?", "About twenty minutes. Same-day pickup is normal for morning calls."], ["Do you buy trucks that were used for towing?", "Constantly. A worn transmission or rear end lowers the offer less than you'd expect, because the truck still has weight and parts value."], ["Is there any fee?", "None. No towing fee, no trip charge, nothing deducted at pickup."], ["Cash or e-transfer?", "Either, your choice, before the vehicle moves."]],
  finalTitle: "Clear the Driveway This Week", finalText: "Tell us what's sitting there. We'll give you a number today and make the space yours again.", finalCta: "Get a Free Offer",
};

export default function CashForCarsChestermerePage() { return <ServicePage data={data} />; }
