import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/lifted-white-suv-junk-car-calgary.jpeg";
import yardImage from "@/assets/images/silver-saturn-used-car-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Irricana | Free Farm & Yard Pickup", description: "Cash for junk cars in Irricana and area. Old farm trucks, long-parked cars and scrap vehicles bought, towed free from yards and acreages, paid on pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-irricana" }, openGraph: { title: "Cash for Junk Cars Irricana | Free Farm & Yard Pickup", description: "Cash for junk cars in Irricana and area. Old farm trucks, long-parked cars and scrap vehicles bought, towed free from yards and acreages, paid on pickup.", url: "https://www.junkacar.ca/cash-for-cars-irricana", type: "website", images: [{ url: heroImage.src, alt: "Old vehicle ready for free farm pickup near Irricana" }] } };

const data: ServicePageData = { path: "/cash-for-cars-irricana", label: "Cash for Cars Irricana", h1: "Cash for Junk Cars in Irricana — Old, Parked or Long Forgotten", subhead: "We're about forty-five minutes southwest of you. If the yard is holding a vehicle that hasn't moved in years, we'll give you an honest answer about what it's worth, tow it free, and pay you before it leaves.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "Older white SUV ready for junk vehicle pickup near Irricana", trustItems: ["Free farm pickup", "Yard clear-outs", "Honest same-day offers", "Paid at pickup"], sections: [
  { eyebrow: "Classic or scrap", title: "Is It a Classic, or Is It a Junk Car?", image: yardImage, imageAlt: "Older vehicle being assessed for collector or scrap value near Irricana", intro: ["We hear this question more in Irricana than anywhere else we serve. It's a town that respects old machinery — Pioneer Acres, the steam engines, the restored tractors that come out for the annual show — and that respect extends to old trucks and cars sitting in yards. Plenty are kept because they might be worth something one day.", "Some are. Most aren't. Here's how to tell the difference honestly, from people who look at yard vehicles for a living."], cards: [
    { title: "What makes an old vehicle genuinely collectible", text: "Collector value depends on a model people actively want, a desirable engine or trim, matching original components, a solid frame and body, and enough completeness that restoring it is realistic. A 1960s or 1970s pickup with a rust-free cab and original drivetrain can have real enthusiast value." },
    { title: "What usually makes it scrap", text: "Frame rot, rusted-through floors and cab corners, a missing or swapped engine, decades in a field with the windows down, and — most commonly — a model with no enthusiast following. A 1990s sedan or minivan is almost never collectible, however old it gets." },
    { title: "Our honest advice", text: "If you genuinely think a vehicle might be collectible, get a collector or restoration shop to look before selling it to anyone — including us. If it is what most yard vehicles are, we'll give you a fair scrap-and-parts number and take it away free." },
  ]},
  { eyebrow: "Why they accumulate", title: "Why Vehicles Stay in Irricana Yards", cards: [
    { title: "Room and time", text: "Irricana lots and farms have space, so there's never pressure to deal with a retired vehicle. A truck parked beside the shop in 2008 may still be there because nothing made it urgent." },
    { title: "Keeping one for parts", text: "A second old truck becomes a parts supply, then a third arrives. As parts are pulled, vehicles become shells — and a stripped shell is worth noticeably less than a complete vehicle." },
    { title: "Estates and generational yards", text: "Many yards have passed down through families, and the vehicles came with them. When a property changes hands, the question of what to do with them often arrives all at once." },
  ]},
  { eyebrow: "Valuation", title: "What Irricana Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Stripped shell used for parts", "$150 – $400"], ["Old car, long-parked, complete", "$250 – $700"], ["Older farm half-ton, complete", "$500 – $1,600"], ["Grain truck or one-ton, complete", "$900 – $3,000"], ["Several vehicles, one yard", "Per-vehicle offer improves"]] }, after: ["Weight sets the floor, and older vehicles are often heavier than modern ones — more steel, thicker frames. Completeness matters more than age. The catalytic converter adds value on anything from the mid-1970s onward; earlier vehicles don't have one, so their value sits almost entirely in weight and parts."] },
  { eyebrow: "One call handles it", title: "Our Services in Irricana", intro: ["Whether it's one forgotten truck or a yard full of them, these services cover Irricana and the surrounding Rocky View farmland — each with free towing and payment on the day."], cards: [
    { title: "Junk Car Removal in Irricana", text: <>Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> brings the winch and skates to remove long-parked vehicles with seized brakes, flat tires or vegetation grown around them.</> },
    { title: "Scrap Car Removal in Irricana", text: <>Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> collects yard vehicles and processes them properly, capturing old oils, fuel and antifreeze rather than leaving them to soak into farmland.</> },
    { title: "Cash for Scrap Cars in Irricana", text: <>Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> explains how weight, completeness and — on anything newer than the mid-seventies — the catalytic converter decide the number.</> },
    { title: "Free Towing in Irricana", text: <><Link href="/free-towing-calgary">Free towing</Link> covers town lots and farms toward Beiseker, Keoma or Kathyrn, including field access, long approaches and multi-vehicle clear-outs.</> },
  ]},
  { eyebrow: "Local situations", title: "Situations We Handle Around Irricana", cards: [{ title: "“There's no paperwork — it's been here forever.”", text: "Very common with old yard vehicles. Call before booking; there's often still a documented route, and we'll tell you what it is." }, { title: "“I don't know what half of them are.”", text: "That's fine. Describe what you can, send photos, and we'll quote the group." }, { title: "“A tree has grown up through it.”", text: "We've seen it more than once. It adds time, not impossibility." }, { title: "“I want to keep the tailgate, badges or steering wheel.”", text: "Tell us what you're keeping and we'll quote around it. Plenty of people hold on to one piece of a family truck." }] },
  { eyebrow: "Before dismantling", title: "Should You Sell the Parts Yourself First?", intro: ["With old vehicles, people often ask whether they'd make more pulling the good parts and selling them online, then scrapping the rest. Occasionally, yes — if a vehicle has one genuinely rare part with an active buyer, it can be worth pulling.", "For most yard vehicles, the maths doesn't work. You'll spend days removing parts that sell slowly, if at all, and every part you pull lowers the offer on the shell. Tell us what you're thinking of pulling and we'll quote it both ways."] },
  { eyebrow: "Coverage", title: "Where We Collect Around Irricana", intro: ["The town of Irricana and surrounding Rocky View County farmland along Highway 9, Highway 72, Highway 806 and Highway 566, including Kathyrn, Beiseker, Keoma, Madden and Crossfield, and toward Acme and Linden. Yard access, field access and long gravel approaches are routine; soft ground is the only real limit."] },
  { eyebrow: "Simple sale", title: "How It Works", intro: ["Describe the vehicle or the whole yard. We come back the same day with a number, including the tow. Pickup is usually next day. On site we complete the bill of sale with you, pay cash or e-transfer, and load.", "You'll need photo ID matching the registered owner and proof of ownership. Your plate stays with you — cancel or transfer the registration at any Alberta registry agent afterward."] },
  { eyebrow: "Nearby", title: "Communities Near Irricana", intro: ["Free towing also covers Airdrie, Strathmore and Chestermere, plus the county land between."] },
], faqs: [["How do I know if my old truck is a collectible?", "Model desirability, originality, frame condition and completeness. If you're unsure, have a restoration shop look first — we'd rather you got the right price."], ["It's been in the yard for thirty years. Is it worth anything?", "Yes — at least its weight in metal. Removal is free either way."], ["Can you take several at once?", "Yes, and it improves the per-vehicle offer."], ["Is there a charge to come out this far?", "No mileage fee, no rural surcharge."], ["How do you pay?", "Cash or e-transfer, before the vehicle moves."]], finalTitle: "Get an Honest Answer", finalText: "Send us a photo. We'll tell you whether it's a classic worth keeping or a junk car worth clearing — and what it's worth either way.", finalCta: "Get a Free Offer" };
export default function CashForCarsIrricanaPage() { return <ServicePage data={data} />; }
