import type { Metadata } from "next";
import Link from "next/link";
import { ServicePage, type ServicePageData } from "@/components/service-page";
import heroImage from "@/assets/images/white-ford-escape-junk-car-calgary.jpeg";
import forestImage from "@/assets/images/lifted-white-suv-junk-car-calgary.jpeg";

export const metadata: Metadata = { title: "Cash for Junk Cars Bragg Creek | Free Treed-Lot Pickup", description: "Cash for junk cars in Bragg Creek. We remove non-running and scrap vehicles from forested acreages and narrow driveways, tow free, and pay on pickup.", alternates: { canonical: "https://www.junkacar.ca/cash-for-cars-bragg-creek" }, openGraph: { title: "Cash for Junk Cars Bragg Creek | Free Treed-Lot Pickup", description: "Cash for junk cars in Bragg Creek. We remove non-running and scrap vehicles from forested acreages and narrow driveways, tow free, and pay on pickup.", url: "https://www.junkacar.ca/cash-for-cars-bragg-creek", type: "website", images: [{ url: heroImage.src, alt: "Junk vehicle ready for pickup from a treed Bragg Creek property" }] } };

const data: ServicePageData = {
  path: "/cash-for-cars-bragg-creek", label: "Cash for Cars Bragg Creek", h1: "Cash for Junk Cars in Bragg Creek — Even From the Back of a Treed Lot",
  subhead: "We're about forty minutes west, into the trees. If there's a vehicle sitting at the end of a winding driveway, under the spruce or behind the shed, we'll plan the extraction properly, tow it free, and pay you before it leaves the property.", primaryCta: "Get My Cash Offer", heroImage, heroAlt: "White Ford Escape awaiting junk car pickup near Bragg Creek", trustItems: ["Free Bragg Creek towing", "Treed lots handled", "Same-day offers", "Paid at pickup"],
  sections: [
    { eyebrow: "Why Bragg Creek is different", title: "Removing a Vehicle From the Forest Isn't Like Removing One From a Driveway", intro: ["Most city pickups are simple: the car sits on pavement, the truck backs up, the car is winched on. In Bragg Creek, almost nothing about that is true, and the planning matters as much as the truck."], cards: [
      { title: "Long, narrow, treed driveways", text: <>Properties in the hamlet, West Bragg Creek, Wintergreen, Bracken and the acreage pockets along Highway 22 and Highway 758 are set back in the trees on purpose. That means long gravel driveways, tight curves, overhanging branches and very little room to turn a truck around at the top.<br /><br />We plan these pickups differently — sometimes backing the full length of a driveway, sometimes winching the vehicle to a wider spot first. The single most helpful thing you can do is tell us roughly how long the driveway is, where the tightest point is, and whether there&apos;s anywhere to turn.</> },
      { title: "Vehicles tucked into the trees", text: <>Out here, a retired vehicle rarely sits in the open. It gets pushed behind the shed, under the spruce, or down at the edge of the property where nobody has to look at it. After a few years, roots, needles and undergrowth have grown in around it, and the ground beneath is soft, uneven and full of roots.<br /><br />That&apos;s all workable. It just takes longer, and it helps enormously to know in advance.</> },
      { title: "Wildlife and rodents move in", text: "A car parked in the forest becomes a home within a season. Mice and packrats nest in air boxes and headliners, chew through wiring harnesses and insulation, and squirrels store food in engine bays. That damage lowers what's salvageable, which is one reason a vehicle left in the trees loses value faster than one left on a paved driveway in town." },
      { title: "It's a fire-season concern", text: "Bragg Creek lives with wildfire awareness, and FireSmart guidance encourages clearing combustible material away from homes and outbuildings. An old vehicle full of dry needles, nesting material and residual fuel and oil is exactly the kind of thing worth removing from a treed property — especially one parked close to the house." },
    ]},
    { eyebrow: "Valuation", title: "What Bragg Creek Junk Cars Are Worth", table: { headings: ["Vehicle", "Typical offer"], rows: [["Long-parked car, rodent-damaged, complete", "$250 – $700"], ["Older SUV or 4x4, non-running", "$500 – $1,800"], ["Truck or diesel, complete", "$900 – $3,500"], ["Stripped or partly dismantled", "$200 – $500"], ["Running vehicle with high kilometres", "$900 – $4,000"]] }, after: ["Weight sets the floor. Salvageable parts push it up — though on long-parked forest vehicles, rodent damage to wiring and interiors often reduces what can be reused. The catalytic converter is valued separately. Current scrap prices move everything.", "The honest summary: a vehicle that's been in the trees for years is usually worth less than the same vehicle parked on pavement. But it's always worth something, and the removal is always free — however far back it sits."] },
    { eyebrow: "One call handles it", title: "Our Services in Bragg Creek", intro: ["Every service below is planned around forested properties — narrow driveways, soft ground and vehicles tucked out of sight — and each comes with free towing and payment on collection."], cards: [
      { title: "Junk Car Removal in Bragg Creek", text: <>Getting a dead vehicle out from under the spruce at the end of a winding West Bragg Creek driveway is a different job from a city pickup. Our <Link href="/junk-car-removal-calgary">junk car removal service</Link> plans the route first — overhead clearance, turnaround space, where to winch from — so the vehicle comes out without damaging your trees or driveway.</> },
      { title: "Scrap Car Removal in Bragg Creek", text: <>A vehicle that&apos;s been rotting in the undergrowth for years is usually a scrap vehicle — and one full of dry needles, nesting material and old fluids in a wildfire area. Our <Link href="/scrap-car-removal-calgary">scrap car removal</Link> takes it away and processes it properly, with oils and fuel captured instead of seeping toward the Elbow River.</> },
      { title: "Cash for Scrap Cars in Bragg Creek", text: <>Rodents chewing through the harness and interior lower what&apos;s salvageable, but they don&apos;t touch the steel, the aluminium or the catalytic converter. Our <Link href="/cash-for-scrap-cars-calgary">cash for scrap cars page</Link> explains exactly which parts of a long-parked forest vehicle still carry value — so you know what to expect before we quote.</> },
      { title: "Free Towing in Bragg Creek", text: <>Forty minutes from Calgary, down a gravel lane, behind a shed — the pickup still costs nothing. <Link href="/free-towing-calgary">Free towing</Link> covers the hamlet, Wintergreen, Bracken, Elbow Valley and the acreages along Highway 22 and 758, with no charge for the extra planning treed lots need.</> },
    ]},
    { eyebrow: "Plan the extraction", title: "What to Tell Us Before We Come Out", cards: [
      { title: "The driveway", text: "Roughly how long it is, whether it's gravel or dirt, where the tightest curve is, and whether a truck can turn around at the top. Photos are ideal." },
      { title: "Where the vehicle sits", text: "On the driveway, behind a building, or out in the trees. If it's in the trees, roughly how far from the nearest point a truck can reach." },
      { title: "The ground", text: "Firm, soft or boggy. Spring melt and fall rain can make forest ground impassable for a loaded truck. If that's the case, we'd rather wait a week than rut your property." },
      { title: "Anything overhead", text: "Low branches or power lines along the driveway. Flat decks are tall and need clearance." },
      { title: "Whether you'll be there", text: "Many Bragg Creek properties are weekend or seasonal. Someone authorised needs to be present to sign and accept payment, but it doesn't have to be the owner if it's arranged in advance." },
    ]},
    { eyebrow: "The easier route", title: "Why Not Just Drag It Out Yourself?", image: forestImage, imageAlt: "White SUV being recovered from a rural property near Bragg Creek", intro: ["Plenty of people in Bragg Creek consider borrowing a neighbour's truck and trailer and hauling the vehicle out themselves. It can work, but it's worth knowing the catches.", "A non-running vehicle with seized brakes doesn't roll onto a trailer; it has to be winched, and a car that's sat in the trees for years often has wheels that won't turn at all. Once it's out, you still have to take it somewhere — and most scrap yards will pay you weight value only, minus nothing for your fuel and your Saturday.", "We bring the winch, the skates and the flat deck, we price for parts and the converter as well as weight, and the tow costs you nothing. For most people, that's simply the easier and better-paying route."] },
    { eyebrow: "Coverage", title: "Where We Collect in and Around Bragg Creek", intro: ["The hamlet and Old Bragg Creek, West Bragg Creek, Wintergreen, Bracken, Elbow Valley, Redwood Meadows, and the acreage and country residential pockets along Highway 22, Highway 758, Highway 8 and Balsam Avenue, out toward Priddis and Millarville.", "We also serve properties near the Elbow River and the edge of Kananaskis Country, where access roads are narrower and conditions change with the season."] },
    { eyebrow: "Four simple steps", title: "How It Works", cards: [{ title: "Describe the vehicle and the access.", text: "Here, the access matters as much as the vehicle." }, { title: "Get a number the same day.", text: "Free towing already inside it." }, { title: "Book a window.", text: "Usually next day for Bragg Creek, with time allowed for planning." }, { title: "Get paid.", text: "Bill of sale, cash or e-transfer, and we take it out." }] },
    { eyebrow: "Ownership", title: "Paperwork", intro: ["Photo ID matching the registered owner and proof of ownership. We write the bill of sale on site.", "Plates stay with you in Alberta. Cancel or transfer the registration at any registry agent afterward, and check with your insurer about unused prepaid coverage.", "Vehicles that came with a property, or belonged to a previous owner of the land, come up regularly out here. If there's no paperwork in your name, call first — there's often still a documented route."] },
    { eyebrow: "Nearby", title: "Communities Near Bragg Creek", intro: ["Free towing also covers Cochrane, Okotoks and Diamond Valley, plus Calgary's southwest and the Rocky View and Foothills County land between."] },
  ],
  faqs: [["Can you get a car out from deep in the trees?", "Usually. We winch it to where the truck can reach. Tell us the distance and the ground conditions."], ["Will you damage my driveway or trees?", "We plan to avoid it. If the ground is too soft or the access too tight, we'll say so rather than force it."], ["Mice have destroyed the interior. Is it still worth anything?", "Yes. It lowers the salvage value, but the weight and metal value remain, and removal is free."], ["The vehicle came with the property and isn't in my name.", "Call before booking. There's often a documented route, but it needs sorting first."], ["Is there any extra charge for coming this far?", "No. No mileage fee and no rural surcharge."], ["How do you pay?", "Cash on the spot or e-transfer, before the vehicle moves."]],
  finalTitle: "Get It Out of the Trees", finalText: "Send us a photo of the driveway and the vehicle. We'll tell you exactly how we'd get it out — and what it's worth.", finalCta: "Get a Free Offer",
};
export default function CashForCarsBraggCreekPage() { return <ServicePage data={data} />; }
